packages:
    - 'libs/*'

autoInstallPeers: false

allowBuilds:
    '@parcel/watcher': true
    esbuild: true
    lefthook: true
    lmdb: true
    msgpackr-extract: true
    nx: true
minimumReleaseAgeExclude:
    - '@angular-devkit/architect@0.2200.7'
    - '@angular-devkit/core@22.0.7'
    - '@angular-devkit/schematics@22.0.7'
    - '@angular/cli@22.0.7'
    - '@schematics/angular@22.0.7'
    - '@angular/build@22.0.7'
    - '@angular/common@22.0.7'
    - '@angular/compiler-cli@22.0.7'
    - '@angular/compiler@22.0.7'
    - '@angular/core@22.0.7'
    - '@angular/forms@22.0.7'
    - '@angular/platform-browser@22.0.7'
    - '@angular/router@22.0.7'
onlyBuiltDependencies:
    - '@touhidrahman/simple-store'
