// This file is auto-generated by @hey-api/openapi-ts

import type {
    Client,
    ClientMeta,
    Options as Options2,
    RequestResult,
    TDataShape,
} from './client'
import { client } from './client.gen'
import {
    deleteProjectsByProjectIdResponseTransformer,
    deleteSecretKeysByIdResponseTransformer,
    getLogsIdResponseTransformer,
    getLogsResponseTransformer,
    getProjectsByProjectIdResponseTransformer,
    getProjectsResponseTransformer,
    getSecretKeysByIdResponseTransformer,
    getSecretKeysResponseTransformer,
    postAdminLoginResponseTransformer,
    postAdminNewTokenResponseTransformer,
    postLogsResponseTransformer,
    postProjectsResponseTransformer,
    postSecretKeysResponseTransformer,
    putProjectsByProjectIdResponseTransformer,
} from './transformers.gen'
import type {
    DeleteLogsEntityEntityIdData,
    DeleteLogsEntityEntityIdErrors,
    DeleteLogsEntityEntityIdResponses,
    DeleteLogsIdData,
    DeleteLogsIdErrors,
    DeleteLogsIdResponses,
    DeleteProjectsByProjectIdData,
    DeleteProjectsByProjectIdResponses,
    DeleteSecretKeysByIdData,
    DeleteSecretKeysByIdResponses,
    GetData,
    GetLogsData,
    GetLogsExportCsvData,
    GetLogsExportCsvResponses,
    GetLogsIdData,
    GetLogsIdErrors,
    GetLogsIdResponses,
    GetLogsResponses,
    GetProjectsByProjectIdData,
    GetProjectsByProjectIdResponses,
    GetProjectsData,
    GetProjectsResponses,
    GetResponses,
    GetSecretKeysByIdData,
    GetSecretKeysByIdResponses,
    GetSecretKeysData,
    GetSecretKeysResponses,
    PostAdminLoginData,
    PostAdminLoginResponses,
    PostAdminNewTokenData,
    PostAdminNewTokenResponses,
    PostLogsData,
    PostLogsErrors,
    PostLogsResponses,
    PostProjectsData,
    PostProjectsResponses,
    PostSecretKeysData,
    PostSecretKeysResponses,
    PutProjectsByProjectIdChangeIdData,
    PutProjectsByProjectIdChangeIdResponses,
    PutProjectsByProjectIdData,
    PutProjectsByProjectIdResponses,
} from './types.gen'

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

export const get = <ThrowOnError extends boolean = false>(
    options?: Options<GetData, ThrowOnError>,
): RequestResult<GetResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<GetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options,
    })

export const postAdminNewToken = <ThrowOnError extends boolean = false>(
    options: Options<PostAdminNewTokenData, ThrowOnError>,
): RequestResult<PostAdminNewTokenResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostAdminNewTokenResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postAdminNewTokenResponseTransformer,
        url: '/admin/new-token',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const postAdminLogin = <ThrowOnError extends boolean = false>(
    options: Options<PostAdminLoginData, ThrowOnError>,
): RequestResult<PostAdminLoginResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostAdminLoginResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postAdminLoginResponseTransformer,
        url: '/admin/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getProjects = <ThrowOnError extends boolean = false>(
    options?: Options<GetProjectsData, ThrowOnError>,
): RequestResult<GetProjectsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetProjectsResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getProjectsResponseTransformer,
        url: '/projects',
        ...options,
    })

export const postProjects = <ThrowOnError extends boolean = false>(
    options?: Options<PostProjectsData, ThrowOnError>,
): RequestResult<PostProjectsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostProjectsResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postProjectsResponseTransformer,
        url: '/projects',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const deleteProjectsByProjectId = <ThrowOnError extends boolean = false>(
    options: Options<DeleteProjectsByProjectIdData, ThrowOnError>,
): RequestResult<DeleteProjectsByProjectIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteProjectsByProjectIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: deleteProjectsByProjectIdResponseTransformer,
        url: '/projects/{projectId}',
        ...options,
    })

export const getProjectsByProjectId = <ThrowOnError extends boolean = false>(
    options: Options<GetProjectsByProjectIdData, ThrowOnError>,
): RequestResult<GetProjectsByProjectIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetProjectsByProjectIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getProjectsByProjectIdResponseTransformer,
        url: '/projects/{projectId}',
        ...options,
    })

export const putProjectsByProjectId = <ThrowOnError extends boolean = false>(
    options: Options<PutProjectsByProjectIdData, ThrowOnError>,
): RequestResult<PutProjectsByProjectIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutProjectsByProjectIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: putProjectsByProjectIdResponseTransformer,
        url: '/projects/{projectId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const putProjectsByProjectIdChangeId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PutProjectsByProjectIdChangeIdData, ThrowOnError>,
): RequestResult<
    PutProjectsByProjectIdChangeIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).put<
        PutProjectsByProjectIdChangeIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/projects/{projectId}/change-id',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getSecretKeys = <ThrowOnError extends boolean = false>(
    options?: Options<GetSecretKeysData, ThrowOnError>,
): RequestResult<GetSecretKeysResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetSecretKeysResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getSecretKeysResponseTransformer,
        url: '/secret-keys',
        ...options,
    })

export const postSecretKeys = <ThrowOnError extends boolean = false>(
    options?: Options<PostSecretKeysData, ThrowOnError>,
): RequestResult<PostSecretKeysResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostSecretKeysResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postSecretKeysResponseTransformer,
        url: '/secret-keys',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const deleteSecretKeysById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteSecretKeysByIdData, ThrowOnError>,
): RequestResult<DeleteSecretKeysByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteSecretKeysByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: deleteSecretKeysByIdResponseTransformer,
        url: '/secret-keys/{id}',
        ...options,
    })

export const getSecretKeysById = <ThrowOnError extends boolean = false>(
    options: Options<GetSecretKeysByIdData, ThrowOnError>,
): RequestResult<GetSecretKeysByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetSecretKeysByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getSecretKeysByIdResponseTransformer,
        url: '/secret-keys/{id}',
        ...options,
    })

export const getLogs = <ThrowOnError extends boolean = false>(
    options?: Options<GetLogsData, ThrowOnError>,
): RequestResult<GetLogsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<GetLogsResponses, unknown, ThrowOnError>({
        responseTransformer: getLogsResponseTransformer,
        url: '/logs',
        ...options,
    })

export const postLogs = <ThrowOnError extends boolean = false>(
    options?: Options<PostLogsData, ThrowOnError>,
): RequestResult<PostLogsResponses, PostLogsErrors, ThrowOnError> =>
    (options?.client ?? client).post<
        PostLogsResponses,
        PostLogsErrors,
        ThrowOnError
    >({
        responseTransformer: postLogsResponseTransformer,
        url: '/logs',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const getLogsExportCsv = <ThrowOnError extends boolean = false>(
    options?: Options<GetLogsExportCsvData, ThrowOnError>,
): RequestResult<GetLogsExportCsvResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetLogsExportCsvResponses,
        unknown,
        ThrowOnError
    >({ url: '/logs/export/csv', ...options })

export const deleteLogsId = <ThrowOnError extends boolean = false>(
    options: Options<DeleteLogsIdData, ThrowOnError>,
): RequestResult<DeleteLogsIdResponses, DeleteLogsIdErrors, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteLogsIdResponses,
        DeleteLogsIdErrors,
        ThrowOnError
    >({ url: '/logs/:id', ...options })

export const getLogsId = <ThrowOnError extends boolean = false>(
    options: Options<GetLogsIdData, ThrowOnError>,
): RequestResult<GetLogsIdResponses, GetLogsIdErrors, ThrowOnError> =>
    (options.client ?? client).get<
        GetLogsIdResponses,
        GetLogsIdErrors,
        ThrowOnError
    >({
        responseTransformer: getLogsIdResponseTransformer,
        url: '/logs/:id',
        ...options,
    })

export const deleteLogsEntityEntityId = <ThrowOnError extends boolean = false>(
    options: Options<DeleteLogsEntityEntityIdData, ThrowOnError>,
): RequestResult<
    DeleteLogsEntityEntityIdResponses,
    DeleteLogsEntityEntityIdErrors,
    ThrowOnError
> =>
    (options.client ?? client).delete<
        DeleteLogsEntityEntityIdResponses,
        DeleteLogsEntityEntityIdErrors,
        ThrowOnError
    >({ url: '/logs/entity/:entityId', ...options })
