// This file is auto-generated by @hey-api/openapi-ts

import type {
    DeleteProjectsByProjectIdResponse,
    DeleteSecretKeysByIdResponse,
    GetLogsIdResponse,
    GetLogsResponse,
    GetProjectsByProjectIdResponse,
    GetProjectsResponse,
    GetSecretKeysByIdResponse,
    GetSecretKeysResponse,
    PostAdminLoginResponse,
    PostAdminNewTokenResponse,
    PostLogsResponse,
    PostProjectsResponse,
    PostSecretKeysResponse,
    PutProjectsByProjectIdResponse,
} from './types.gen'

export const postAdminNewTokenResponseTransformer = async (
    data: any,
): Promise<PostAdminNewTokenResponse> => {
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    return data
}

export const postAdminLoginResponseTransformer = async (
    data: any,
): Promise<PostAdminLoginResponse> => {
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    return data
}

export const getProjectsResponseTransformer = async (
    data: any,
): Promise<GetProjectsResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const postProjectsResponseTransformer = async (
    data: any,
): Promise<PostProjectsResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const deleteProjectsByProjectIdResponseTransformer = async (
    data: any,
): Promise<DeleteProjectsByProjectIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getProjectsByProjectIdResponseTransformer = async (
    data: any,
): Promise<GetProjectsByProjectIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const putProjectsByProjectIdResponseTransformer = async (
    data: any,
): Promise<PutProjectsByProjectIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getSecretKeysResponseTransformer = async (
    data: any,
): Promise<GetSecretKeysResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.expiresAt) {
            item.expiresAt = new Date(item.expiresAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        return item
    })
    return data
}

export const postSecretKeysResponseTransformer = async (
    data: any,
): Promise<PostSecretKeysResponse> => {
    if (data.data.expiresAt) {
        data.data.expiresAt = new Date(data.data.expiresAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    return data
}

export const deleteSecretKeysByIdResponseTransformer = async (
    data: any,
): Promise<DeleteSecretKeysByIdResponse> => {
    if (data.data.expiresAt) {
        data.data.expiresAt = new Date(data.data.expiresAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    return data
}

export const getSecretKeysByIdResponseTransformer = async (
    data: any,
): Promise<GetSecretKeysByIdResponse> => {
    if (data.data.expiresAt) {
        data.data.expiresAt = new Date(data.data.expiresAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    return data
}

export const getLogsResponseTransformer = async (
    data: any,
): Promise<GetLogsResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const postLogsResponseTransformer = async (
    data: any,
): Promise<PostLogsResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getLogsIdResponseTransformer = async (
    data: any,
): Promise<GetLogsIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}
