// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://auditlog-api.mattrika.com' | (string & {})
}

export type GetData = {
    body?: never
    path?: never
    query?: never
    url: '/'
}

export type GetResponses = {
    /**
     * Server running
     */
    200: {
        data: {
            port: number
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type GetResponse = GetResponses[keyof GetResponses]

export type PostAdminNewTokenData = {
    /**
     * Refresh token
     */
    body: {
        refreshToken: string
    }
    path?: never
    query?: never
    url: '/admin/new-token'
}

export type PostAdminNewTokenResponses = {
    /**
     * User logged in successfully
     */
    200: {
        data: {
            accessToken: string
            refreshToken: string
            lastLogin?: Date
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type PostAdminNewTokenResponse =
    PostAdminNewTokenResponses[keyof PostAdminNewTokenResponses]

export type PostAdminLoginData = {
    /**
     * Admin Login Data
     */
    body: {
        password: string
    }
    path?: never
    query?: never
    url: '/admin/login'
}

export type PostAdminLoginResponses = {
    /**
     * Admin logged in successfully
     */
    200: {
        data: {
            accessToken: string
            refreshToken: string
            lastLogin?: Date
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type PostAdminLoginResponse =
    PostAdminLoginResponses[keyof PostAdminLoginResponses]

export type GetProjectsData = {
    body?: never
    path?: never
    query?: {
        id?: string
        name?: string
        icon?: string | null
        color?: string | null
        createdAt?: Date | null
        updatedAt?: Date | null
        search?: string
        ids?: Array<string>
        orderBy?: string
        sortOrder?: 'asc' | 'desc'
        page?: number
        size?: number
    }
    url: '/projects'
}

export type GetProjectsResponses = {
    /**
     * Project List
     */
    200: {
        data: Array<{
            id: string
            name: string
            icon: string | null
            color: string | null
            createdAt: Date | null
            updatedAt: Date | null
        }>
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
        pagination: {
            page: number
            size: number
            totalItems: number
            totalPages: number
        }
    }
}

export type GetProjectsResponse =
    GetProjectsResponses[keyof GetProjectsResponses]

export type PostProjectsData = {
    /**
     * Input
     */
    body?: {
        id?: string
        name: string
        icon?: string | null
        color?: string | null
        createdAt?: Date | null
        updatedAt?: Date | null
    }
    path?: never
    query?: never
    url: '/projects'
}

export type PostProjectsResponses = {
    /**
     * Item
     */
    200: {
        data: {
            id: string
            name: string
            icon: string | null
            color: string | null
            createdAt: Date | null
            updatedAt: Date | null
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type PostProjectsResponse =
    PostProjectsResponses[keyof PostProjectsResponses]

export type DeleteProjectsByProjectIdData = {
    body?: never
    path: {
        projectId: string
    }
    query?: never
    url: '/projects/{projectId}'
}

export type DeleteProjectsByProjectIdResponses = {
    /**
     * Deleted Project
     */
    200: {
        data: {
            id: string
            name: string
            icon: string | null
            color: string | null
            createdAt: Date | null
            updatedAt: Date | null
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type DeleteProjectsByProjectIdResponse =
    DeleteProjectsByProjectIdResponses[keyof DeleteProjectsByProjectIdResponses]

export type GetProjectsByProjectIdData = {
    body?: never
    path: {
        projectId: string
    }
    query?: never
    url: '/projects/{projectId}'
}

export type GetProjectsByProjectIdResponses = {
    /**
     * Item
     */
    200: {
        data: {
            id: string
            name: string
            icon: string | null
            color: string | null
            createdAt: Date | null
            updatedAt: Date | null
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type GetProjectsByProjectIdResponse =
    GetProjectsByProjectIdResponses[keyof GetProjectsByProjectIdResponses]

export type PutProjectsByProjectIdData = {
    /**
     * Input
     */
    body?: {
        id?: string
        name?: string
        icon?: string | null
        color?: string | null
        createdAt?: Date | null
        updatedAt?: Date | null
    }
    path: {
        projectId: string
    }
    query?: never
    url: '/projects/{projectId}'
}

export type PutProjectsByProjectIdResponses = {
    /**
     * Item
     */
    200: {
        data: {
            id: string
            name: string
            icon: string | null
            color: string | null
            createdAt: Date | null
            updatedAt: Date | null
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type PutProjectsByProjectIdResponse =
    PutProjectsByProjectIdResponses[keyof PutProjectsByProjectIdResponses]

export type PutProjectsByProjectIdChangeIdData = {
    /**
     * New Project ID payload
     */
    body?: {
        newId: string
    }
    path: {
        projectId: string
    }
    query?: never
    url: '/projects/{projectId}/change-id'
}

export type PutProjectsByProjectIdChangeIdResponses = {
    /**
     * Updated Project ID
     */
    200: {
        data: {
            id: string
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type PutProjectsByProjectIdChangeIdResponse =
    PutProjectsByProjectIdChangeIdResponses[keyof PutProjectsByProjectIdChangeIdResponses]

export type GetSecretKeysData = {
    body?: never
    path?: never
    query?: {
        id?: string
        projectId?: string
        secretHash?: string
        expiresAt?: Date | null
        createdAt?: Date | null
        search?: string
        ids?: Array<string>
        orderBy?: string
        sortOrder?: 'asc' | 'desc'
        page?: number
        size?: number
    }
    url: '/secret-keys'
}

export type GetSecretKeysResponses = {
    /**
     * SecretKey List
     */
    200: {
        data: Array<{
            id: string
            projectId: string
            expiresAt: Date | null
            createdAt: Date | null
        }>
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
        pagination: {
            page: number
            size: number
            totalItems: number
            totalPages: number
        }
    }
}

export type GetSecretKeysResponse =
    GetSecretKeysResponses[keyof GetSecretKeysResponses]

export type PostSecretKeysData = {
    /**
     * Input
     */
    body?: {
        expiresAt?: Date | null
    }
    path?: never
    query?: never
    url: '/secret-keys'
}

export type PostSecretKeysResponses = {
    /**
     * Item
     */
    200: {
        data: {
            id: string
            projectId: string
            expiresAt: Date | null
            createdAt: Date | null
            secretKey: string
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type PostSecretKeysResponse =
    PostSecretKeysResponses[keyof PostSecretKeysResponses]

export type DeleteSecretKeysByIdData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: '/secret-keys/{id}'
}

export type DeleteSecretKeysByIdResponses = {
    /**
     * Deleted SecretKey
     */
    200: {
        data: {
            id: string
            projectId: string
            secretHash: string
            expiresAt: Date | null
            createdAt: Date | null
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type DeleteSecretKeysByIdResponse =
    DeleteSecretKeysByIdResponses[keyof DeleteSecretKeysByIdResponses]

export type GetSecretKeysByIdData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: '/secret-keys/{id}'
}

export type GetSecretKeysByIdResponses = {
    /**
     * Item
     */
    200: {
        data: {
            id: string
            projectId: string
            expiresAt: Date | null
            createdAt: Date | null
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type GetSecretKeysByIdResponse =
    GetSecretKeysByIdResponses[keyof GetSecretKeysByIdResponses]

export type GetLogsData = {
    body?: never
    path?: never
    query?: {
        id?: string
        entity?: string
        entityId?: string
        creatorId?: string | null
        creatorName?: string | null
        projectId?: string
        action?: 'create' | 'update' | 'delete'
        previousData?:
            | string
            | number
            | boolean
            | unknown
            | {
                  [key: string]: unknown
              }
            | Array<unknown>
        updatedData?:
            | string
            | number
            | boolean
            | unknown
            | {
                  [key: string]: unknown
              }
            | Array<unknown>
        createdAt?: Date | null
        updatedAt?: Date | null
        search?: string
        ids?: Array<string>
        orderBy?: string
        sortOrder?: 'asc' | 'desc'
        page?: number
        size?: number
        dateFrom?: string
        dateTo?: string
    }
    url: '/logs'
}

export type GetLogsResponses = {
    /**
     * List of logs
     */
    200: {
        data: Array<{
            id?: string
            entity?: string
            entityId?: string
            creatorId?: string | null
            creatorName?: string | null
            projectId?: string
            action?: 'create' | 'update' | 'delete'
            previousData?:
                | string
                | number
                | boolean
                | unknown
                | {
                      [key: string]: unknown
                  }
                | Array<unknown>
            updatedData?:
                | string
                | number
                | boolean
                | unknown
                | {
                      [key: string]: unknown
                  }
                | Array<unknown>
            createdAt?: Date | null
            updatedAt?: Date | null
        }>
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
        pagination: {
            page: number
            size: number
            totalItems: number
            totalPages: number
        }
    }
}

export type GetLogsResponse = GetLogsResponses[keyof GetLogsResponses]

export type PostLogsData = {
    /**
     * Log details
     */
    body?: {
        id?: string
        entity: string
        entityId: string
        creatorId?: string | null
        creatorName?: string | null
        projectId: string
        action: 'create' | 'update' | 'delete'
        previousData?:
            | string
            | number
            | boolean
            | unknown
            | {
                  [key: string]: unknown
              }
            | Array<unknown>
        updatedData?:
            | string
            | number
            | boolean
            | unknown
            | {
                  [key: string]: unknown
              }
            | Array<unknown>
        createdAt?: Date | null
        updatedAt?: Date | null
    }
    path?: never
    query?: never
    url: '/logs'
}

export type PostLogsErrors = {
    /**
     * Invalid log data
     */
    400: {
        data: {
            [key: string]: unknown
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
    /**
     * Internal server error
     */
    500: {
        data: {
            [key: string]: unknown
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type PostLogsError = PostLogsErrors[keyof PostLogsErrors]

export type PostLogsResponses = {
    /**
     * Log created successfully
     */
    201: {
        data: {
            id?: string
            entity?: string
            entityId?: string
            creatorId?: string | null
            creatorName?: string | null
            projectId?: string
            action?: 'create' | 'update' | 'delete'
            previousData?:
                | string
                | number
                | boolean
                | unknown
                | {
                      [key: string]: unknown
                  }
                | Array<unknown>
            updatedData?:
                | string
                | number
                | boolean
                | unknown
                | {
                      [key: string]: unknown
                  }
                | Array<unknown>
            createdAt?: Date | null
            updatedAt?: Date | null
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type PostLogsResponse = PostLogsResponses[keyof PostLogsResponses]

export type GetLogsExportCsvData = {
    body?: never
    path?: never
    query?: {
        id?: string
        entity?: string
        entityId?: string
        creatorId?: string | null
        creatorName?: string | null
        projectId?: string
        action?: 'create' | 'update' | 'delete'
        previousData?:
            | string
            | number
            | boolean
            | unknown
            | {
                  [key: string]: unknown
              }
            | Array<unknown>
        updatedData?:
            | string
            | number
            | boolean
            | unknown
            | {
                  [key: string]: unknown
              }
            | Array<unknown>
        createdAt?: Date | null
        updatedAt?: Date | null
        search?: string
        ids?: Array<string>
        orderBy?: string
        sortOrder?: 'asc' | 'desc'
        page?: number
        size?: number
        dateFrom?: string
        dateTo?: string
    }
    url: '/logs/export/csv'
}

export type GetLogsExportCsvResponses = {
    /**
     * CSV file with logs data
     */
    200: string
}

export type GetLogsExportCsvResponse =
    GetLogsExportCsvResponses[keyof GetLogsExportCsvResponses]

export type DeleteLogsIdData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: '/logs/:id'
}

export type DeleteLogsIdErrors = {
    /**
     * Log not found
     */
    404: {
        data: {
            [key: string]: unknown
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
    /**
     * Internal server error
     */
    500: {
        data: {
            [key: string]: unknown
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type DeleteLogsIdError = DeleteLogsIdErrors[keyof DeleteLogsIdErrors]

export type DeleteLogsIdResponses = {
    /**
     * Log deleted successfully
     */
    200: {
        data: {
            [key: string]: unknown
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type DeleteLogsIdResponse =
    DeleteLogsIdResponses[keyof DeleteLogsIdResponses]

export type GetLogsIdData = {
    body?: never
    path: {
        id: string
    }
    query?: never
    url: '/logs/:id'
}

export type GetLogsIdErrors = {
    /**
     * Log not found
     */
    404: {
        data: {
            [key: string]: unknown
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type GetLogsIdError = GetLogsIdErrors[keyof GetLogsIdErrors]

export type GetLogsIdResponses = {
    /**
     * Log found
     */
    200: {
        data: {
            id?: string
            entity?: string
            entityId?: string
            creatorId?: string | null
            creatorName?: string | null
            projectId?: string
            action?: 'create' | 'update' | 'delete'
            previousData?:
                | string
                | number
                | boolean
                | unknown
                | {
                      [key: string]: unknown
                  }
                | Array<unknown>
            updatedData?:
                | string
                | number
                | boolean
                | unknown
                | {
                      [key: string]: unknown
                  }
                | Array<unknown>
            createdAt?: Date | null
            updatedAt?: Date | null
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type GetLogsIdResponse = GetLogsIdResponses[keyof GetLogsIdResponses]

export type DeleteLogsEntityEntityIdData = {
    body?: never
    path: {
        entityId: string
    }
    query?: never
    url: '/logs/entity/:entityId'
}

export type DeleteLogsEntityEntityIdErrors = {
    /**
     * Internal server error
     */
    500: {
        data: {
            [key: string]: unknown
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type DeleteLogsEntityEntityIdError =
    DeleteLogsEntityEntityIdErrors[keyof DeleteLogsEntityEntityIdErrors]

export type DeleteLogsEntityEntityIdResponses = {
    /**
     * Logs deleted successfully
     */
    200: {
        data: {
            [key: string]: unknown
        }
        message: string
        success: boolean
        error?: unknown
        meta?: unknown
    }
}

export type DeleteLogsEntityEntityIdResponse =
    DeleteLogsEntityEntityIdResponses[keyof DeleteLogsEntityEntityIdResponses]
