// This file is auto-generated by @hey-api/openapi-ts

import type {
    DeleteGroupsByIdResponse,
    DeleteInvitesByIdResponse,
    DeleteMembershipsByIdResponse,
    DeleteOrganizationsByIdResponse,
    DeleteOrganizationsByOrganizationIdBranchesByIdResponse,
    DeleteOrganizationsByOrganizationIdZonesByIdResponse,
    DeleteProjectsByProjectIdResponse,
    DeleteRolesByIdResponse,
    DeleteSecretKeysByIdResponse,
    DeleteUsersByIdMembershipsByMembershipIdResponse,
    DeleteUsersByIdResponse,
    GetGroupsByIdResponse,
    GetGroupsByIdUsersResponse,
    GetGroupsMyResponse,
    GetGroupsResponse,
    GetInvitesByIdResponse,
    GetInvitesResponse,
    GetMembershipsBranchByIdResponse,
    GetMembershipsByIdResponse,
    GetMembershipsMyResponse,
    GetMembershipsResponse,
    GetMembershipsZoneByZoneIdResponse,
    GetOrganizationsByIdResponse,
    GetOrganizationsByOrganizationIdBranchesByIdResponse,
    GetOrganizationsByOrganizationIdBranchesMyResponse,
    GetOrganizationsByOrganizationIdBranchesResponse,
    GetOrganizationsByOrganizationIdCreatorResponse,
    GetOrganizationsByOrganizationIdMembersResponse,
    GetOrganizationsByOrganizationIdZonesByIdResponse,
    GetOrganizationsByOrganizationIdZonesMyResponse,
    GetOrganizationsByOrganizationIdZonesResponse,
    GetOrganizationsByOwnerByUserIdResponse,
    GetOrganizationsByUserByUserIdResponse,
    GetOrganizationsResponse,
    GetProjectsByProjectIdResponse,
    GetProjectsResponse,
    GetRolesByIdResponse,
    GetRolesByIdUsersResponse,
    GetRolesResponse,
    GetSecretKeysByIdResponse,
    GetSecretKeysResponse,
    GetUsersByIdIdentifiersResponse,
    GetUsersByIdResponse,
    GetUsersCustomActiveResponse,
    GetUsersCustomBannedResponse,
    GetUsersCustomInactiveResponse,
    GetUsersCustomUnverifiedResponse,
    GetUsersMeResponse,
    GetUsersResponse,
    PostAdminLoginResponse,
    PostAdminNewTokenResponse,
    PostGroupsResponse,
    PostInvitesResponse,
    PostMembershipsByIdBranchResponse,
    PostMembershipsByIdZoneResponse,
    PostMembershipsResponse,
    PostOrganizationsByOrganizationIdBranchesResponse,
    PostOrganizationsByOrganizationIdZonesResponse,
    PostOrganizationsResponse,
    PostProjectsResponse,
    PostRolesResponse,
    PostSecretKeysResponse,
    PostUserPasswordsUpsertResponse,
    PostUsersByIdPasswordChangeResponse,
    PostUsersLoginResponse,
    PostUsersLoginSwitchResponse,
    PostUsersPasswordResetByTokenResponse,
    PostUsersRegisterResponse,
    PostUsersResponse,
    PutGroupsByIdResponse,
    PutInvitesByIdResponse,
    PutOrganizationsByIdResponse,
    PutOrganizationsByOrganizationIdBranchesByIdResponse,
    PutOrganizationsByOrganizationIdZonesByIdResponse,
    PutProjectsByProjectIdResponse,
    PutRolesByIdResponse,
    PutUsersByIdResponse,
} from './types.gen'

export const postAdminNewTokenResponseTransformer = async (
    data: any,
): Promise<PostAdminNewTokenResponse> => {
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    return data
}

export const postAdminLoginResponseTransformer = async (
    data: any,
): Promise<PostAdminLoginResponse> => {
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    return data
}

export const getOrganizationsByOrganizationIdBranchesMyResponseTransformer =
    async (
        data: any,
    ): Promise<GetOrganizationsByOrganizationIdBranchesMyResponse> => {
        data.data = data.data.map((item: any) => {
            if (item.createdAt) {
                item.createdAt = new Date(item.createdAt)
            }
            if (item.updatedAt) {
                item.updatedAt = new Date(item.updatedAt)
            }
            return item
        })
        return data
    }

export const getOrganizationsByOrganizationIdBranchesResponseTransformer =
    async (
        data: any,
    ): Promise<GetOrganizationsByOrganizationIdBranchesResponse> => {
        data.data = data.data.map((item: any) => {
            if (item.createdAt) {
                item.createdAt = new Date(item.createdAt)
            }
            if (item.updatedAt) {
                item.updatedAt = new Date(item.updatedAt)
            }
            return item
        })
        return data
    }

export const postOrganizationsByOrganizationIdBranchesResponseTransformer =
    async (
        data: any,
    ): Promise<PostOrganizationsByOrganizationIdBranchesResponse> => {
        if (data.data.createdAt) {
            data.data.createdAt = new Date(data.data.createdAt)
        }
        if (data.data.updatedAt) {
            data.data.updatedAt = new Date(data.data.updatedAt)
        }
        return data
    }

export const deleteOrganizationsByOrganizationIdBranchesByIdResponseTransformer =
    async (
        data: any,
    ): Promise<DeleteOrganizationsByOrganizationIdBranchesByIdResponse> => {
        if (data.data.createdAt) {
            data.data.createdAt = new Date(data.data.createdAt)
        }
        if (data.data.updatedAt) {
            data.data.updatedAt = new Date(data.data.updatedAt)
        }
        return data
    }

export const getOrganizationsByOrganizationIdBranchesByIdResponseTransformer =
    async (
        data: any,
    ): Promise<GetOrganizationsByOrganizationIdBranchesByIdResponse> => {
        if (data.data.createdAt) {
            data.data.createdAt = new Date(data.data.createdAt)
        }
        if (data.data.updatedAt) {
            data.data.updatedAt = new Date(data.data.updatedAt)
        }
        return data
    }

export const putOrganizationsByOrganizationIdBranchesByIdResponseTransformer =
    async (
        data: any,
    ): Promise<PutOrganizationsByOrganizationIdBranchesByIdResponse> => {
        if (data.data.createdAt) {
            data.data.createdAt = new Date(data.data.createdAt)
        }
        if (data.data.updatedAt) {
            data.data.updatedAt = new Date(data.data.updatedAt)
        }
        return data
    }

export const getGroupsMyResponseTransformer = async (
    data: any,
): Promise<GetGroupsMyResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const getGroupsByIdUsersResponseTransformer = async (
    data: any,
): Promise<GetGroupsByIdUsersResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.lastLogin) {
            item.lastLogin = new Date(item.lastLogin)
        }
        if (item.bannedAt) {
            item.bannedAt = new Date(item.bannedAt)
        }
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const getGroupsResponseTransformer = async (
    data: any,
): Promise<GetGroupsResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const postGroupsResponseTransformer = async (
    data: any,
): Promise<PostGroupsResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const deleteGroupsByIdResponseTransformer = async (
    data: any,
): Promise<DeleteGroupsByIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getGroupsByIdResponseTransformer = async (
    data: any,
): Promise<GetGroupsByIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const putGroupsByIdResponseTransformer = async (
    data: any,
): Promise<PutGroupsByIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getInvitesResponseTransformer = async (
    data: any,
): Promise<GetInvitesResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.expiresAt) {
            item.expiresAt = new Date(item.expiresAt)
        }
        if (item.acceptedAt) {
            item.acceptedAt = new Date(item.acceptedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const postInvitesResponseTransformer = async (
    data: any,
): Promise<PostInvitesResponse> => {
    if (data.data.expiresAt) {
        data.data.expiresAt = new Date(data.data.expiresAt)
    }
    if (data.data.acceptedAt) {
        data.data.acceptedAt = new Date(data.data.acceptedAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const deleteInvitesByIdResponseTransformer = async (
    data: any,
): Promise<DeleteInvitesByIdResponse> => {
    if (data.data.expiresAt) {
        data.data.expiresAt = new Date(data.data.expiresAt)
    }
    if (data.data.acceptedAt) {
        data.data.acceptedAt = new Date(data.data.acceptedAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getInvitesByIdResponseTransformer = async (
    data: any,
): Promise<GetInvitesByIdResponse> => {
    if (data.data.expiresAt) {
        data.data.expiresAt = new Date(data.data.expiresAt)
    }
    if (data.data.acceptedAt) {
        data.data.acceptedAt = new Date(data.data.acceptedAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const putInvitesByIdResponseTransformer = async (
    data: any,
): Promise<PutInvitesByIdResponse> => {
    if (data.data.expiresAt) {
        data.data.expiresAt = new Date(data.data.expiresAt)
    }
    if (data.data.acceptedAt) {
        data.data.acceptedAt = new Date(data.data.acceptedAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const postMembershipsByIdZoneResponseTransformer = async (
    data: any,
): Promise<PostMembershipsByIdZoneResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getMembershipsZoneByZoneIdResponseTransformer = async (
    data: any,
): Promise<GetMembershipsZoneByZoneIdResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const postMembershipsByIdBranchResponseTransformer = async (
    data: any,
): Promise<PostMembershipsByIdBranchResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getMembershipsBranchByIdResponseTransformer = async (
    data: any,
): Promise<GetMembershipsBranchByIdResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const getMembershipsMyResponseTransformer = async (
    data: any,
): Promise<GetMembershipsMyResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const getMembershipsResponseTransformer = async (
    data: any,
): Promise<GetMembershipsResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        if (item.project) {
            if (item.project.createdAt) {
                item.project.createdAt = new Date(item.project.createdAt)
            }
            if (item.project.updatedAt) {
                item.project.updatedAt = new Date(item.project.updatedAt)
            }
        }
        if (item.user) {
            if (item.user.lastLogin) {
                item.user.lastLogin = new Date(item.user.lastLogin)
            }
            if (item.user.bannedAt) {
                item.user.bannedAt = new Date(item.user.bannedAt)
            }
            if (item.user.verifiedAt) {
                item.user.verifiedAt = new Date(item.user.verifiedAt)
            }
            if (item.user.createdAt) {
                item.user.createdAt = new Date(item.user.createdAt)
            }
            if (item.user.updatedAt) {
                item.user.updatedAt = new Date(item.user.updatedAt)
            }
        }
        if (item.role) {
            if (item.role.createdAt) {
                item.role.createdAt = new Date(item.role.createdAt)
            }
            if (item.role.updatedAt) {
                item.role.updatedAt = new Date(item.role.updatedAt)
            }
        }
        if (item.group) {
            if (item.group.createdAt) {
                item.group.createdAt = new Date(item.group.createdAt)
            }
            if (item.group.updatedAt) {
                item.group.updatedAt = new Date(item.group.updatedAt)
            }
        }
        if (item.organization) {
            if (item.organization.createdAt) {
                item.organization.createdAt = new Date(
                    item.organization.createdAt,
                )
            }
            if (item.organization.updatedAt) {
                item.organization.updatedAt = new Date(
                    item.organization.updatedAt,
                )
            }
        }
        return item
    })
    return data
}

export const postMembershipsResponseTransformer = async (
    data: any,
): Promise<PostMembershipsResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    if (data.data.project) {
        if (data.data.project.createdAt) {
            data.data.project.createdAt = new Date(data.data.project.createdAt)
        }
        if (data.data.project.updatedAt) {
            data.data.project.updatedAt = new Date(data.data.project.updatedAt)
        }
    }
    if (data.data.user) {
        if (data.data.user.lastLogin) {
            data.data.user.lastLogin = new Date(data.data.user.lastLogin)
        }
        if (data.data.user.bannedAt) {
            data.data.user.bannedAt = new Date(data.data.user.bannedAt)
        }
        if (data.data.user.verifiedAt) {
            data.data.user.verifiedAt = new Date(data.data.user.verifiedAt)
        }
        if (data.data.user.createdAt) {
            data.data.user.createdAt = new Date(data.data.user.createdAt)
        }
        if (data.data.user.updatedAt) {
            data.data.user.updatedAt = new Date(data.data.user.updatedAt)
        }
    }
    if (data.data.role) {
        if (data.data.role.createdAt) {
            data.data.role.createdAt = new Date(data.data.role.createdAt)
        }
        if (data.data.role.updatedAt) {
            data.data.role.updatedAt = new Date(data.data.role.updatedAt)
        }
    }
    if (data.data.group) {
        if (data.data.group.createdAt) {
            data.data.group.createdAt = new Date(data.data.group.createdAt)
        }
        if (data.data.group.updatedAt) {
            data.data.group.updatedAt = new Date(data.data.group.updatedAt)
        }
    }
    if (data.data.organization) {
        if (data.data.organization.createdAt) {
            data.data.organization.createdAt = new Date(
                data.data.organization.createdAt,
            )
        }
        if (data.data.organization.updatedAt) {
            data.data.organization.updatedAt = new Date(
                data.data.organization.updatedAt,
            )
        }
    }
    return data
}

export const deleteMembershipsByIdResponseTransformer = async (
    data: any,
): Promise<DeleteMembershipsByIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getMembershipsByIdResponseTransformer = async (
    data: any,
): Promise<GetMembershipsByIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getOrganizationsByUserByUserIdResponseTransformer = async (
    data: any,
): Promise<GetOrganizationsByUserByUserIdResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const getOrganizationsByOwnerByUserIdResponseTransformer = async (
    data: any,
): Promise<GetOrganizationsByOwnerByUserIdResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const getOrganizationsByOrganizationIdMembersResponseTransformer =
    async (
        data: any,
    ): Promise<GetOrganizationsByOrganizationIdMembersResponse> => {
        data.data = data.data.map((item: any) => {
            if (item.lastLogin) {
                item.lastLogin = new Date(item.lastLogin)
            }
            if (item.bannedAt) {
                item.bannedAt = new Date(item.bannedAt)
            }
            if (item.verifiedAt) {
                item.verifiedAt = new Date(item.verifiedAt)
            }
            if (item.createdAt) {
                item.createdAt = new Date(item.createdAt)
            }
            if (item.updatedAt) {
                item.updatedAt = new Date(item.updatedAt)
            }
            return item
        })
        return data
    }

export const getOrganizationsByOrganizationIdCreatorResponseTransformer =
    async (
        data: any,
    ): Promise<GetOrganizationsByOrganizationIdCreatorResponse> => {
        if (data.data.lastLogin) {
            data.data.lastLogin = new Date(data.data.lastLogin)
        }
        if (data.data.bannedAt) {
            data.data.bannedAt = new Date(data.data.bannedAt)
        }
        if (data.data.verifiedAt) {
            data.data.verifiedAt = new Date(data.data.verifiedAt)
        }
        if (data.data.createdAt) {
            data.data.createdAt = new Date(data.data.createdAt)
        }
        if (data.data.updatedAt) {
            data.data.updatedAt = new Date(data.data.updatedAt)
        }
        return data
    }

export const getOrganizationsResponseTransformer = async (
    data: any,
): Promise<GetOrganizationsResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const postOrganizationsResponseTransformer = async (
    data: any,
): Promise<PostOrganizationsResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const deleteOrganizationsByIdResponseTransformer = async (
    data: any,
): Promise<DeleteOrganizationsByIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getOrganizationsByIdResponseTransformer = async (
    data: any,
): Promise<GetOrganizationsByIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const putOrganizationsByIdResponseTransformer = async (
    data: any,
): Promise<PutOrganizationsByIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getProjectsResponseTransformer = async (
    data: any,
): Promise<GetProjectsResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const postProjectsResponseTransformer = async (
    data: any,
): Promise<PostProjectsResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const deleteProjectsByProjectIdResponseTransformer = async (
    data: any,
): Promise<DeleteProjectsByProjectIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getProjectsByProjectIdResponseTransformer = async (
    data: any,
): Promise<GetProjectsByProjectIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const putProjectsByProjectIdResponseTransformer = async (
    data: any,
): Promise<PutProjectsByProjectIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getRolesByIdUsersResponseTransformer = async (
    data: any,
): Promise<GetRolesByIdUsersResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.lastLogin) {
            item.lastLogin = new Date(item.lastLogin)
        }
        if (item.bannedAt) {
            item.bannedAt = new Date(item.bannedAt)
        }
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const getRolesResponseTransformer = async (
    data: any,
): Promise<GetRolesResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const postRolesResponseTransformer = async (
    data: any,
): Promise<PostRolesResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const deleteRolesByIdResponseTransformer = async (
    data: any,
): Promise<DeleteRolesByIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getRolesByIdResponseTransformer = async (
    data: any,
): Promise<GetRolesByIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const putRolesByIdResponseTransformer = async (
    data: any,
): Promise<PutRolesByIdResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getSecretKeysResponseTransformer = async (
    data: any,
): Promise<GetSecretKeysResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.expiresAt) {
            item.expiresAt = new Date(item.expiresAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        return item
    })
    return data
}

export const postSecretKeysResponseTransformer = async (
    data: any,
): Promise<PostSecretKeysResponse> => {
    if (data.data.expiresAt) {
        data.data.expiresAt = new Date(data.data.expiresAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    return data
}

export const deleteSecretKeysByIdResponseTransformer = async (
    data: any,
): Promise<DeleteSecretKeysByIdResponse> => {
    if (data.data.expiresAt) {
        data.data.expiresAt = new Date(data.data.expiresAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    return data
}

export const getSecretKeysByIdResponseTransformer = async (
    data: any,
): Promise<GetSecretKeysByIdResponse> => {
    if (data.data.expiresAt) {
        data.data.expiresAt = new Date(data.data.expiresAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    return data
}

export const getUsersByIdIdentifiersResponseTransformer = async (
    data: any,
): Promise<GetUsersByIdIdentifiersResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const postUserPasswordsUpsertResponseTransformer = async (
    data: any,
): Promise<PostUserPasswordsUpsertResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const deleteUsersByIdMembershipsByMembershipIdResponseTransformer =
    async (
        data: any,
    ): Promise<DeleteUsersByIdMembershipsByMembershipIdResponse> => {
        if (data.data.createdAt) {
            data.data.createdAt = new Date(data.data.createdAt)
        }
        if (data.data.updatedAt) {
            data.data.updatedAt = new Date(data.data.updatedAt)
        }
        return data
    }

export const postUsersPasswordResetByTokenResponseTransformer = async (
    data: any,
): Promise<PostUsersPasswordResetByTokenResponse> => {
    if (data.data.user.lastLogin) {
        data.data.user.lastLogin = new Date(data.data.user.lastLogin)
    }
    if (data.data.user.bannedAt) {
        data.data.user.bannedAt = new Date(data.data.user.bannedAt)
    }
    if (data.data.user.verifiedAt) {
        data.data.user.verifiedAt = new Date(data.data.user.verifiedAt)
    }
    if (data.data.user.createdAt) {
        data.data.user.createdAt = new Date(data.data.user.createdAt)
    }
    if (data.data.user.updatedAt) {
        data.data.user.updatedAt = new Date(data.data.user.updatedAt)
    }
    data.data.userIdentifiers = data.data.userIdentifiers.map((item: any) => {
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    if (data.data.role) {
        if (data.data.role.createdAt) {
            data.data.role.createdAt = new Date(data.data.role.createdAt)
        }
        if (data.data.role.updatedAt) {
            data.data.role.updatedAt = new Date(data.data.role.updatedAt)
        }
    }
    if (data.data.organization) {
        if (data.data.organization.createdAt) {
            data.data.organization.createdAt = new Date(
                data.data.organization.createdAt,
            )
        }
        if (data.data.organization.updatedAt) {
            data.data.organization.updatedAt = new Date(
                data.data.organization.updatedAt,
            )
        }
    }
    if (data.data.group) {
        if (data.data.group.createdAt) {
            data.data.group.createdAt = new Date(data.data.group.createdAt)
        }
        if (data.data.group.updatedAt) {
            data.data.group.updatedAt = new Date(data.data.group.updatedAt)
        }
    }
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    return data
}

export const postUsersByIdPasswordChangeResponseTransformer = async (
    data: any,
): Promise<PostUsersByIdPasswordChangeResponse> => {
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    if (data.data.bannedAt) {
        data.data.bannedAt = new Date(data.data.bannedAt)
    }
    if (data.data.verifiedAt) {
        data.data.verifiedAt = new Date(data.data.verifiedAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const postUsersLoginResponseTransformer = async (
    data: any,
): Promise<PostUsersLoginResponse> => {
    if (data.data.user.lastLogin) {
        data.data.user.lastLogin = new Date(data.data.user.lastLogin)
    }
    if (data.data.user.bannedAt) {
        data.data.user.bannedAt = new Date(data.data.user.bannedAt)
    }
    if (data.data.user.verifiedAt) {
        data.data.user.verifiedAt = new Date(data.data.user.verifiedAt)
    }
    if (data.data.user.createdAt) {
        data.data.user.createdAt = new Date(data.data.user.createdAt)
    }
    if (data.data.user.updatedAt) {
        data.data.user.updatedAt = new Date(data.data.user.updatedAt)
    }
    data.data.userIdentifiers = data.data.userIdentifiers.map((item: any) => {
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    if (data.data.role) {
        if (data.data.role.createdAt) {
            data.data.role.createdAt = new Date(data.data.role.createdAt)
        }
        if (data.data.role.updatedAt) {
            data.data.role.updatedAt = new Date(data.data.role.updatedAt)
        }
    }
    if (data.data.organization) {
        if (data.data.organization.createdAt) {
            data.data.organization.createdAt = new Date(
                data.data.organization.createdAt,
            )
        }
        if (data.data.organization.updatedAt) {
            data.data.organization.updatedAt = new Date(
                data.data.organization.updatedAt,
            )
        }
    }
    if (data.data.group) {
        if (data.data.group.createdAt) {
            data.data.group.createdAt = new Date(data.data.group.createdAt)
        }
        if (data.data.group.updatedAt) {
            data.data.group.updatedAt = new Date(data.data.group.updatedAt)
        }
    }
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    return data
}

export const postUsersLoginSwitchResponseTransformer = async (
    data: any,
): Promise<PostUsersLoginSwitchResponse> => {
    if (data.data.user.lastLogin) {
        data.data.user.lastLogin = new Date(data.data.user.lastLogin)
    }
    if (data.data.user.bannedAt) {
        data.data.user.bannedAt = new Date(data.data.user.bannedAt)
    }
    if (data.data.user.verifiedAt) {
        data.data.user.verifiedAt = new Date(data.data.user.verifiedAt)
    }
    if (data.data.user.createdAt) {
        data.data.user.createdAt = new Date(data.data.user.createdAt)
    }
    if (data.data.user.updatedAt) {
        data.data.user.updatedAt = new Date(data.data.user.updatedAt)
    }
    data.data.userIdentifiers = data.data.userIdentifiers.map((item: any) => {
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    if (data.data.role) {
        if (data.data.role.createdAt) {
            data.data.role.createdAt = new Date(data.data.role.createdAt)
        }
        if (data.data.role.updatedAt) {
            data.data.role.updatedAt = new Date(data.data.role.updatedAt)
        }
    }
    if (data.data.organization) {
        if (data.data.organization.createdAt) {
            data.data.organization.createdAt = new Date(
                data.data.organization.createdAt,
            )
        }
        if (data.data.organization.updatedAt) {
            data.data.organization.updatedAt = new Date(
                data.data.organization.updatedAt,
            )
        }
    }
    if (data.data.group) {
        if (data.data.group.createdAt) {
            data.data.group.createdAt = new Date(data.data.group.createdAt)
        }
        if (data.data.group.updatedAt) {
            data.data.group.updatedAt = new Date(data.data.group.updatedAt)
        }
    }
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    return data
}

export const postUsersRegisterResponseTransformer = async (
    data: any,
): Promise<PostUsersRegisterResponse> => {
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    if (data.data.bannedAt) {
        data.data.bannedAt = new Date(data.data.bannedAt)
    }
    if (data.data.verifiedAt) {
        data.data.verifiedAt = new Date(data.data.verifiedAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getUsersMeResponseTransformer = async (
    data: any,
): Promise<GetUsersMeResponse> => {
    if (data.data.user.lastLogin) {
        data.data.user.lastLogin = new Date(data.data.user.lastLogin)
    }
    if (data.data.user.bannedAt) {
        data.data.user.bannedAt = new Date(data.data.user.bannedAt)
    }
    if (data.data.user.verifiedAt) {
        data.data.user.verifiedAt = new Date(data.data.user.verifiedAt)
    }
    if (data.data.user.createdAt) {
        data.data.user.createdAt = new Date(data.data.user.createdAt)
    }
    if (data.data.user.updatedAt) {
        data.data.user.updatedAt = new Date(data.data.user.updatedAt)
    }
    data.data.userIdentifiers = data.data.userIdentifiers.map((item: any) => {
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    if (data.data.role) {
        if (data.data.role.createdAt) {
            data.data.role.createdAt = new Date(data.data.role.createdAt)
        }
        if (data.data.role.updatedAt) {
            data.data.role.updatedAt = new Date(data.data.role.updatedAt)
        }
    }
    if (data.data.organization) {
        if (data.data.organization.createdAt) {
            data.data.organization.createdAt = new Date(
                data.data.organization.createdAt,
            )
        }
        if (data.data.organization.updatedAt) {
            data.data.organization.updatedAt = new Date(
                data.data.organization.updatedAt,
            )
        }
    }
    if (data.data.group) {
        if (data.data.group.createdAt) {
            data.data.group.createdAt = new Date(data.data.group.createdAt)
        }
        if (data.data.group.updatedAt) {
            data.data.group.updatedAt = new Date(data.data.group.updatedAt)
        }
    }
    return data
}

export const getUsersCustomActiveResponseTransformer = async (
    data: any,
): Promise<GetUsersCustomActiveResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.lastLogin) {
            item.lastLogin = new Date(item.lastLogin)
        }
        if (item.bannedAt) {
            item.bannedAt = new Date(item.bannedAt)
        }
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const getUsersCustomBannedResponseTransformer = async (
    data: any,
): Promise<GetUsersCustomBannedResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.lastLogin) {
            item.lastLogin = new Date(item.lastLogin)
        }
        if (item.bannedAt) {
            item.bannedAt = new Date(item.bannedAt)
        }
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const getUsersCustomUnverifiedResponseTransformer = async (
    data: any,
): Promise<GetUsersCustomUnverifiedResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.lastLogin) {
            item.lastLogin = new Date(item.lastLogin)
        }
        if (item.bannedAt) {
            item.bannedAt = new Date(item.bannedAt)
        }
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const getUsersCustomInactiveResponseTransformer = async (
    data: any,
): Promise<GetUsersCustomInactiveResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.lastLogin) {
            item.lastLogin = new Date(item.lastLogin)
        }
        if (item.bannedAt) {
            item.bannedAt = new Date(item.bannedAt)
        }
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const getUsersResponseTransformer = async (
    data: any,
): Promise<GetUsersResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.lastLogin) {
            item.lastLogin = new Date(item.lastLogin)
        }
        if (item.bannedAt) {
            item.bannedAt = new Date(item.bannedAt)
        }
        if (item.verifiedAt) {
            item.verifiedAt = new Date(item.verifiedAt)
        }
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const postUsersResponseTransformer = async (
    data: any,
): Promise<PostUsersResponse> => {
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    if (data.data.bannedAt) {
        data.data.bannedAt = new Date(data.data.bannedAt)
    }
    if (data.data.verifiedAt) {
        data.data.verifiedAt = new Date(data.data.verifiedAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const deleteUsersByIdResponseTransformer = async (
    data: any,
): Promise<DeleteUsersByIdResponse> => {
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    if (data.data.bannedAt) {
        data.data.bannedAt = new Date(data.data.bannedAt)
    }
    if (data.data.verifiedAt) {
        data.data.verifiedAt = new Date(data.data.verifiedAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getUsersByIdResponseTransformer = async (
    data: any,
): Promise<GetUsersByIdResponse> => {
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    if (data.data.bannedAt) {
        data.data.bannedAt = new Date(data.data.bannedAt)
    }
    if (data.data.verifiedAt) {
        data.data.verifiedAt = new Date(data.data.verifiedAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const putUsersByIdResponseTransformer = async (
    data: any,
): Promise<PutUsersByIdResponse> => {
    if (data.data.lastLogin) {
        data.data.lastLogin = new Date(data.data.lastLogin)
    }
    if (data.data.bannedAt) {
        data.data.bannedAt = new Date(data.data.bannedAt)
    }
    if (data.data.verifiedAt) {
        data.data.verifiedAt = new Date(data.data.verifiedAt)
    }
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const getOrganizationsByOrganizationIdZonesMyResponseTransformer =
    async (
        data: any,
    ): Promise<GetOrganizationsByOrganizationIdZonesMyResponse> => {
        data.data = data.data.map((item: any) => {
            if (item.createdAt) {
                item.createdAt = new Date(item.createdAt)
            }
            if (item.updatedAt) {
                item.updatedAt = new Date(item.updatedAt)
            }
            return item
        })
        return data
    }

export const getOrganizationsByOrganizationIdZonesResponseTransformer = async (
    data: any,
): Promise<GetOrganizationsByOrganizationIdZonesResponse> => {
    data.data = data.data.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt)
        }
        if (item.updatedAt) {
            item.updatedAt = new Date(item.updatedAt)
        }
        return item
    })
    return data
}

export const postOrganizationsByOrganizationIdZonesResponseTransformer = async (
    data: any,
): Promise<PostOrganizationsByOrganizationIdZonesResponse> => {
    if (data.data.createdAt) {
        data.data.createdAt = new Date(data.data.createdAt)
    }
    if (data.data.updatedAt) {
        data.data.updatedAt = new Date(data.data.updatedAt)
    }
    return data
}

export const deleteOrganizationsByOrganizationIdZonesByIdResponseTransformer =
    async (
        data: any,
    ): Promise<DeleteOrganizationsByOrganizationIdZonesByIdResponse> => {
        if (data.data.createdAt) {
            data.data.createdAt = new Date(data.data.createdAt)
        }
        if (data.data.updatedAt) {
            data.data.updatedAt = new Date(data.data.updatedAt)
        }
        return data
    }

export const getOrganizationsByOrganizationIdZonesByIdResponseTransformer =
    async (
        data: any,
    ): Promise<GetOrganizationsByOrganizationIdZonesByIdResponse> => {
        if (data.data.createdAt) {
            data.data.createdAt = new Date(data.data.createdAt)
        }
        if (data.data.updatedAt) {
            data.data.updatedAt = new Date(data.data.updatedAt)
        }
        return data
    }

export const putOrganizationsByOrganizationIdZonesByIdResponseTransformer =
    async (
        data: any,
    ): Promise<PutOrganizationsByOrganizationIdZonesByIdResponse> => {
        if (data.data.createdAt) {
            data.data.createdAt = new Date(data.data.createdAt)
        }
        if (data.data.updatedAt) {
            data.data.updatedAt = new Date(data.data.updatedAt)
        }
        return data
    }
