// This file is auto-generated by @hey-api/openapi-ts

import type {
    Client,
    ClientMeta,
    Options as Options2,
    RequestResult,
    TDataShape,
} from './client'
import { client } from './client.gen'
import {
    deleteGroupsByIdResponseTransformer,
    deleteInvitesByIdResponseTransformer,
    deleteMembershipsByIdResponseTransformer,
    deleteOrganizationsByIdResponseTransformer,
    deleteOrganizationsByOrganizationIdBranchesByIdResponseTransformer,
    deleteOrganizationsByOrganizationIdZonesByIdResponseTransformer,
    deleteProjectsByProjectIdResponseTransformer,
    deleteRolesByIdResponseTransformer,
    deleteSecretKeysByIdResponseTransformer,
    deleteUsersByIdMembershipsByMembershipIdResponseTransformer,
    deleteUsersByIdResponseTransformer,
    getGroupsByIdResponseTransformer,
    getGroupsByIdUsersResponseTransformer,
    getGroupsMyResponseTransformer,
    getGroupsResponseTransformer,
    getInvitesByIdResponseTransformer,
    getInvitesResponseTransformer,
    getMembershipsBranchByIdResponseTransformer,
    getMembershipsByIdResponseTransformer,
    getMembershipsMyResponseTransformer,
    getMembershipsResponseTransformer,
    getMembershipsZoneByZoneIdResponseTransformer,
    getOrganizationsByIdResponseTransformer,
    getOrganizationsByOrganizationIdBranchesByIdResponseTransformer,
    getOrganizationsByOrganizationIdBranchesMyResponseTransformer,
    getOrganizationsByOrganizationIdBranchesResponseTransformer,
    getOrganizationsByOrganizationIdCreatorResponseTransformer,
    getOrganizationsByOrganizationIdMembersResponseTransformer,
    getOrganizationsByOrganizationIdZonesByIdResponseTransformer,
    getOrganizationsByOrganizationIdZonesMyResponseTransformer,
    getOrganizationsByOrganizationIdZonesResponseTransformer,
    getOrganizationsByOwnerByUserIdResponseTransformer,
    getOrganizationsByUserByUserIdResponseTransformer,
    getOrganizationsResponseTransformer,
    getProjectsByProjectIdResponseTransformer,
    getProjectsResponseTransformer,
    getRolesByIdResponseTransformer,
    getRolesByIdUsersResponseTransformer,
    getRolesResponseTransformer,
    getSecretKeysByIdResponseTransformer,
    getSecretKeysResponseTransformer,
    getUsersByIdIdentifiersResponseTransformer,
    getUsersByIdResponseTransformer,
    getUsersCustomActiveResponseTransformer,
    getUsersCustomBannedResponseTransformer,
    getUsersCustomInactiveResponseTransformer,
    getUsersCustomUnverifiedResponseTransformer,
    getUsersMeResponseTransformer,
    getUsersResponseTransformer,
    postAdminLoginResponseTransformer,
    postAdminNewTokenResponseTransformer,
    postGroupsResponseTransformer,
    postInvitesResponseTransformer,
    postMembershipsByIdBranchResponseTransformer,
    postMembershipsByIdZoneResponseTransformer,
    postMembershipsResponseTransformer,
    postOrganizationsByOrganizationIdBranchesResponseTransformer,
    postOrganizationsByOrganizationIdZonesResponseTransformer,
    postOrganizationsResponseTransformer,
    postProjectsResponseTransformer,
    postRolesResponseTransformer,
    postSecretKeysResponseTransformer,
    postUserPasswordsUpsertResponseTransformer,
    postUsersByIdPasswordChangeResponseTransformer,
    postUsersLoginResponseTransformer,
    postUsersLoginSwitchResponseTransformer,
    postUsersPasswordResetByTokenResponseTransformer,
    postUsersRegisterResponseTransformer,
    postUsersResponseTransformer,
    putGroupsByIdResponseTransformer,
    putInvitesByIdResponseTransformer,
    putOrganizationsByIdResponseTransformer,
    putOrganizationsByOrganizationIdBranchesByIdResponseTransformer,
    putOrganizationsByOrganizationIdZonesByIdResponseTransformer,
    putProjectsByProjectIdResponseTransformer,
    putRolesByIdResponseTransformer,
    putUsersByIdResponseTransformer,
} from './transformers.gen'
import type {
    DeleteGroupsByGroupIdUsersByUserIdData,
    DeleteGroupsByGroupIdUsersByUserIdResponses,
    DeleteGroupsByIdData,
    DeleteGroupsByIdResponses,
    DeleteInvitesByIdData,
    DeleteInvitesByIdResponses,
    DeleteMembershipsByIdBranchData,
    DeleteMembershipsByIdBranchResponses,
    DeleteMembershipsByIdData,
    DeleteMembershipsByIdResponses,
    DeleteMembershipsByIdZoneData,
    DeleteMembershipsByIdZoneResponses,
    DeleteMembershipsData,
    DeleteMembershipsResponses,
    DeleteOrganizationsByIdData,
    DeleteOrganizationsByIdResponses,
    DeleteOrganizationsByOrganizationIdBranchesByIdData,
    DeleteOrganizationsByOrganizationIdBranchesByIdResponses,
    DeleteOrganizationsByOrganizationIdZonesByIdData,
    DeleteOrganizationsByOrganizationIdZonesByIdResponses,
    DeletePermissionsByIdData,
    DeletePermissionsByIdResponses,
    DeleteProjectsByProjectIdData,
    DeleteProjectsByProjectIdResponses,
    DeleteRolesByIdData,
    DeleteRolesByIdPermissionsData,
    DeleteRolesByIdPermissionsResponses,
    DeleteRolesByIdResponses,
    DeleteSecretKeysByIdData,
    DeleteSecretKeysByIdResponses,
    DeleteUsersByIdData,
    DeleteUsersByIdMembershipsByMembershipIdData,
    DeleteUsersByIdMembershipsByMembershipIdResponses,
    DeleteUsersByIdResponses,
    DeleteUsersData,
    DeleteUsersErrors,
    DeleteUsersResponses,
    GetData,
    GetGroupsByIdData,
    GetGroupsByIdPermissionsData,
    GetGroupsByIdPermissionsResponses,
    GetGroupsByIdResponses,
    GetGroupsByIdUsersData,
    GetGroupsByIdUsersResponses,
    GetGroupsData,
    GetGroupsMyData,
    GetGroupsMyResponses,
    GetGroupsResponses,
    GetInvitesByIdData,
    GetInvitesByIdResponses,
    GetInvitesData,
    GetInvitesResponses,
    GetMembershipsBranchByIdData,
    GetMembershipsBranchByIdResponses,
    GetMembershipsByIdData,
    GetMembershipsByIdPermissionsData,
    GetMembershipsByIdPermissionsResponses,
    GetMembershipsByIdResponses,
    GetMembershipsData,
    GetMembershipsMyData,
    GetMembershipsMyResponses,
    GetMembershipsResponses,
    GetMembershipsZoneByZoneIdData,
    GetMembershipsZoneByZoneIdResponses,
    GetOrganizationsByIdData,
    GetOrganizationsByIdResponses,
    GetOrganizationsByOrganizationIdBranchesByIdData,
    GetOrganizationsByOrganizationIdBranchesByIdResponses,
    GetOrganizationsByOrganizationIdBranchesData,
    GetOrganizationsByOrganizationIdBranchesMyData,
    GetOrganizationsByOrganizationIdBranchesMyResponses,
    GetOrganizationsByOrganizationIdBranchesResponses,
    GetOrganizationsByOrganizationIdCreatorData,
    GetOrganizationsByOrganizationIdCreatorResponses,
    GetOrganizationsByOrganizationIdMembersData,
    GetOrganizationsByOrganizationIdMembersResponses,
    GetOrganizationsByOrganizationIdZonesByIdData,
    GetOrganizationsByOrganizationIdZonesByIdResponses,
    GetOrganizationsByOrganizationIdZonesData,
    GetOrganizationsByOrganizationIdZonesMyData,
    GetOrganizationsByOrganizationIdZonesMyResponses,
    GetOrganizationsByOrganizationIdZonesResponses,
    GetOrganizationsByOwnerByUserIdData,
    GetOrganizationsByOwnerByUserIdResponses,
    GetOrganizationsByUserByUserIdData,
    GetOrganizationsByUserByUserIdResponses,
    GetOrganizationsData,
    GetOrganizationsResponses,
    GetPermissionsByIdData,
    GetPermissionsByIdResponses,
    GetPermissionsData,
    GetPermissionsResponses,
    GetProjectsByProjectIdData,
    GetProjectsByProjectIdResponses,
    GetProjectsData,
    GetProjectsResponses,
    GetResponses,
    GetRolesByIdData,
    GetRolesByIdPermissionsData,
    GetRolesByIdPermissionsResponses,
    GetRolesByIdResponses,
    GetRolesByIdUsersData,
    GetRolesByIdUsersResponses,
    GetRolesData,
    GetRolesResponses,
    GetSecretKeysByIdData,
    GetSecretKeysByIdResponses,
    GetSecretKeysData,
    GetSecretKeysResponses,
    GetUserPasswordsData,
    GetUserPasswordsResponses,
    GetUsersByIdData,
    GetUsersByIdIdentifiersData,
    GetUsersByIdIdentifiersResponses,
    GetUsersByIdResponses,
    GetUsersCustomActiveData,
    GetUsersCustomActiveResponses,
    GetUsersCustomBannedData,
    GetUsersCustomBannedResponses,
    GetUsersCustomInactiveData,
    GetUsersCustomInactiveResponses,
    GetUsersCustomUnverifiedData,
    GetUsersCustomUnverifiedResponses,
    GetUsersData,
    GetUsersMeData,
    GetUsersMeResponses,
    GetUsersResponses,
    PostAdminLoginData,
    PostAdminLoginResponses,
    PostAdminNewTokenData,
    PostAdminNewTokenResponses,
    PostGroupsByIdPermissionsData,
    PostGroupsByIdPermissionsResponses,
    PostGroupsData,
    PostGroupsResponses,
    PostInvitesData,
    PostInvitesResponses,
    PostMembershipsByIdBranchData,
    PostMembershipsByIdBranchResponses,
    PostMembershipsByIdZoneData,
    PostMembershipsByIdZoneResponses,
    PostMembershipsData,
    PostMembershipsResponses,
    PostOrganizationsByOrganizationIdBranchesData,
    PostOrganizationsByOrganizationIdBranchesResponses,
    PostOrganizationsByOrganizationIdZonesData,
    PostOrganizationsByOrganizationIdZonesResponses,
    PostOrganizationsData,
    PostOrganizationsResponses,
    PostPermissionsData,
    PostPermissionsResponses,
    PostProjectsData,
    PostProjectsResponses,
    PostRolesByIdPermissionsData,
    PostRolesByIdPermissionsResponses,
    PostRolesData,
    PostRolesErrors,
    PostRolesResponses,
    PostSecretKeysData,
    PostSecretKeysResponses,
    PostUserPasswordsUpsertData,
    PostUserPasswordsUpsertResponses,
    PostUsersByIdIdentifierAddData,
    PostUsersByIdIdentifierAddResponses,
    PostUsersByIdIdentifierDeleteData,
    PostUsersByIdIdentifierDeleteResponses,
    PostUsersByIdNewVerificationTokenData,
    PostUsersByIdNewVerificationTokenResponses,
    PostUsersByIdPasswordChangeData,
    PostUsersByIdPasswordChangeResponses,
    PostUsersData,
    PostUsersLoginData,
    PostUsersLoginResponses,
    PostUsersLoginSwitchData,
    PostUsersLoginSwitchResponses,
    PostUsersLogoutData,
    PostUsersLogoutResponses,
    PostUsersPasswordForgotData,
    PostUsersPasswordForgotResponses,
    PostUsersPasswordResetByTokenData,
    PostUsersPasswordResetByTokenResponses,
    PostUsersRegisterData,
    PostUsersRegisterResponses,
    PostUsersResponses,
    PostUsersTokenData,
    PostUsersTokenResponses,
    PostUsersVerifyByTokenData,
    PostUsersVerifyByTokenResponses,
    PutGroupsByIdChangeIdData,
    PutGroupsByIdChangeIdResponses,
    PutGroupsByIdData,
    PutGroupsByIdResponses,
    PutInvitesByIdChangeIdData,
    PutInvitesByIdChangeIdResponses,
    PutInvitesByIdData,
    PutInvitesByIdResponses,
    PutMembershipsByIdChangeIdData,
    PutMembershipsByIdChangeIdResponses,
    PutOrganizationsByIdChangeIdData,
    PutOrganizationsByIdChangeIdResponses,
    PutOrganizationsByIdData,
    PutOrganizationsByIdResponses,
    PutOrganizationsByOrganizationIdBranchesByIdChangeIdData,
    PutOrganizationsByOrganizationIdBranchesByIdChangeIdResponses,
    PutOrganizationsByOrganizationIdBranchesByIdData,
    PutOrganizationsByOrganizationIdBranchesByIdResponses,
    PutOrganizationsByOrganizationIdZonesByIdChangeIdData,
    PutOrganizationsByOrganizationIdZonesByIdChangeIdResponses,
    PutOrganizationsByOrganizationIdZonesByIdData,
    PutOrganizationsByOrganizationIdZonesByIdResponses,
    PutPermissionsByIdData,
    PutPermissionsByIdResponses,
    PutProjectsByProjectIdChangeIdData,
    PutProjectsByProjectIdChangeIdResponses,
    PutProjectsByProjectIdData,
    PutProjectsByProjectIdResponses,
    PutRolesByIdChangeIdData,
    PutRolesByIdChangeIdResponses,
    PutRolesByIdData,
    PutRolesByIdResponses,
    PutUsersByIdChangeIdData,
    PutUsersByIdChangeIdResponses,
    PutUsersByIdData,
    PutUsersByIdResponses,
} from './types.gen'

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

export const get = <ThrowOnError extends boolean = false>(
    options?: Options<GetData, ThrowOnError>,
): RequestResult<GetResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<GetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options,
    })

export const postAdminNewToken = <ThrowOnError extends boolean = false>(
    options: Options<PostAdminNewTokenData, ThrowOnError>,
): RequestResult<PostAdminNewTokenResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostAdminNewTokenResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postAdminNewTokenResponseTransformer,
        url: '/admin/new-token',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const postAdminLogin = <ThrowOnError extends boolean = false>(
    options: Options<PostAdminLoginData, ThrowOnError>,
): RequestResult<PostAdminLoginResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostAdminLoginResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postAdminLoginResponseTransformer,
        url: '/admin/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getOrganizationsByOrganizationIdBranchesMy = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetOrganizationsByOrganizationIdBranchesMyData,
        ThrowOnError
    >,
): RequestResult<
    GetOrganizationsByOrganizationIdBranchesMyResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetOrganizationsByOrganizationIdBranchesMyResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            getOrganizationsByOrganizationIdBranchesMyResponseTransformer,
        url: '/organizations/{organizationId}/branches/my',
        ...options,
    })

export const getOrganizationsByOrganizationIdBranches = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetOrganizationsByOrganizationIdBranchesData,
        ThrowOnError
    >,
): RequestResult<
    GetOrganizationsByOrganizationIdBranchesResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetOrganizationsByOrganizationIdBranchesResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            getOrganizationsByOrganizationIdBranchesResponseTransformer,
        url: '/organizations/{organizationId}/branches',
        ...options,
    })

export const postOrganizationsByOrganizationIdBranches = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        PostOrganizationsByOrganizationIdBranchesData,
        ThrowOnError
    >,
): RequestResult<
    PostOrganizationsByOrganizationIdBranchesResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).post<
        PostOrganizationsByOrganizationIdBranchesResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            postOrganizationsByOrganizationIdBranchesResponseTransformer,
        url: '/organizations/{organizationId}/branches',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const deleteOrganizationsByOrganizationIdBranchesById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        DeleteOrganizationsByOrganizationIdBranchesByIdData,
        ThrowOnError
    >,
): RequestResult<
    DeleteOrganizationsByOrganizationIdBranchesByIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).delete<
        DeleteOrganizationsByOrganizationIdBranchesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            deleteOrganizationsByOrganizationIdBranchesByIdResponseTransformer,
        url: '/organizations/{organizationId}/branches/{id}',
        ...options,
    })

export const getOrganizationsByOrganizationIdBranchesById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetOrganizationsByOrganizationIdBranchesByIdData,
        ThrowOnError
    >,
): RequestResult<
    GetOrganizationsByOrganizationIdBranchesByIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetOrganizationsByOrganizationIdBranchesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            getOrganizationsByOrganizationIdBranchesByIdResponseTransformer,
        url: '/organizations/{organizationId}/branches/{id}',
        ...options,
    })

export const putOrganizationsByOrganizationIdBranchesById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        PutOrganizationsByOrganizationIdBranchesByIdData,
        ThrowOnError
    >,
): RequestResult<
    PutOrganizationsByOrganizationIdBranchesByIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).put<
        PutOrganizationsByOrganizationIdBranchesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            putOrganizationsByOrganizationIdBranchesByIdResponseTransformer,
        url: '/organizations/{organizationId}/branches/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const putOrganizationsByOrganizationIdBranchesByIdChangeId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        PutOrganizationsByOrganizationIdBranchesByIdChangeIdData,
        ThrowOnError
    >,
): RequestResult<
    PutOrganizationsByOrganizationIdBranchesByIdChangeIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).put<
        PutOrganizationsByOrganizationIdBranchesByIdChangeIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/organizations/{organizationId}/branches/{id}/change-id',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getGroupsMy = <ThrowOnError extends boolean = false>(
    options?: Options<GetGroupsMyData, ThrowOnError>,
): RequestResult<GetGroupsMyResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetGroupsMyResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getGroupsMyResponseTransformer,
        url: '/groups/my',
        ...options,
    })

export const getGroupsByIdPermissions = <ThrowOnError extends boolean = false>(
    options: Options<GetGroupsByIdPermissionsData, ThrowOnError>,
): RequestResult<GetGroupsByIdPermissionsResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetGroupsByIdPermissionsResponses,
        unknown,
        ThrowOnError
    >({ url: '/groups/{id}/permissions', ...options })

export const postGroupsByIdPermissions = <ThrowOnError extends boolean = false>(
    options: Options<PostGroupsByIdPermissionsData, ThrowOnError>,
): RequestResult<PostGroupsByIdPermissionsResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostGroupsByIdPermissionsResponses,
        unknown,
        ThrowOnError
    >({
        url: '/groups/{id}/permissions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getGroupsByIdUsers = <ThrowOnError extends boolean = false>(
    options: Options<GetGroupsByIdUsersData, ThrowOnError>,
): RequestResult<GetGroupsByIdUsersResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetGroupsByIdUsersResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getGroupsByIdUsersResponseTransformer,
        url: '/groups/{id}/users',
        ...options,
    })

export const deleteGroupsByGroupIdUsersByUserId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<DeleteGroupsByGroupIdUsersByUserIdData, ThrowOnError>,
): RequestResult<
    DeleteGroupsByGroupIdUsersByUserIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).delete<
        DeleteGroupsByGroupIdUsersByUserIdResponses,
        unknown,
        ThrowOnError
    >({ url: '/groups/{groupId}/users/{userId}', ...options })

export const getGroups = <ThrowOnError extends boolean = false>(
    options?: Options<GetGroupsData, ThrowOnError>,
): RequestResult<GetGroupsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<GetGroupsResponses, unknown, ThrowOnError>({
        responseTransformer: getGroupsResponseTransformer,
        url: '/groups',
        ...options,
    })

export const postGroups = <ThrowOnError extends boolean = false>(
    options?: Options<PostGroupsData, ThrowOnError>,
): RequestResult<PostGroupsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostGroupsResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postGroupsResponseTransformer,
        url: '/groups',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const deleteGroupsById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteGroupsByIdData, ThrowOnError>,
): RequestResult<DeleteGroupsByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteGroupsByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: deleteGroupsByIdResponseTransformer,
        url: '/groups/{id}',
        ...options,
    })

export const getGroupsById = <ThrowOnError extends boolean = false>(
    options: Options<GetGroupsByIdData, ThrowOnError>,
): RequestResult<GetGroupsByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetGroupsByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getGroupsByIdResponseTransformer,
        url: '/groups/{id}',
        ...options,
    })

export const putGroupsById = <ThrowOnError extends boolean = false>(
    options: Options<PutGroupsByIdData, ThrowOnError>,
): RequestResult<PutGroupsByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutGroupsByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: putGroupsByIdResponseTransformer,
        url: '/groups/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const putGroupsByIdChangeId = <ThrowOnError extends boolean = false>(
    options: Options<PutGroupsByIdChangeIdData, ThrowOnError>,
): RequestResult<PutGroupsByIdChangeIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutGroupsByIdChangeIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/groups/{id}/change-id',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getInvites = <ThrowOnError extends boolean = false>(
    options?: Options<GetInvitesData, ThrowOnError>,
): RequestResult<GetInvitesResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<GetInvitesResponses, unknown, ThrowOnError>(
        {
            responseTransformer: getInvitesResponseTransformer,
            url: '/invites',
            ...options,
        },
    )

export const postInvites = <ThrowOnError extends boolean = false>(
    options?: Options<PostInvitesData, ThrowOnError>,
): RequestResult<PostInvitesResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostInvitesResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postInvitesResponseTransformer,
        url: '/invites',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const deleteInvitesById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteInvitesByIdData, ThrowOnError>,
): RequestResult<DeleteInvitesByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteInvitesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: deleteInvitesByIdResponseTransformer,
        url: '/invites/{id}',
        ...options,
    })

export const getInvitesById = <ThrowOnError extends boolean = false>(
    options: Options<GetInvitesByIdData, ThrowOnError>,
): RequestResult<GetInvitesByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetInvitesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getInvitesByIdResponseTransformer,
        url: '/invites/{id}',
        ...options,
    })

export const putInvitesById = <ThrowOnError extends boolean = false>(
    options: Options<PutInvitesByIdData, ThrowOnError>,
): RequestResult<PutInvitesByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutInvitesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: putInvitesByIdResponseTransformer,
        url: '/invites/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const putInvitesByIdChangeId = <ThrowOnError extends boolean = false>(
    options: Options<PutInvitesByIdChangeIdData, ThrowOnError>,
): RequestResult<PutInvitesByIdChangeIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutInvitesByIdChangeIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/invites/{id}/change-id',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const deleteMembershipsByIdZone = <ThrowOnError extends boolean = false>(
    options: Options<DeleteMembershipsByIdZoneData, ThrowOnError>,
): RequestResult<DeleteMembershipsByIdZoneResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteMembershipsByIdZoneResponses,
        unknown,
        ThrowOnError
    >({
        url: '/memberships/{id}/zone',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const postMembershipsByIdZone = <ThrowOnError extends boolean = false>(
    options: Options<PostMembershipsByIdZoneData, ThrowOnError>,
): RequestResult<PostMembershipsByIdZoneResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostMembershipsByIdZoneResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postMembershipsByIdZoneResponseTransformer,
        url: '/memberships/{id}/zone',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getMembershipsZoneByZoneId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetMembershipsZoneByZoneIdData, ThrowOnError>,
): RequestResult<GetMembershipsZoneByZoneIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetMembershipsZoneByZoneIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getMembershipsZoneByZoneIdResponseTransformer,
        url: '/memberships/zone/{zoneId}',
        ...options,
    })

export const deleteMembershipsByIdBranch = <
    ThrowOnError extends boolean = false,
>(
    options: Options<DeleteMembershipsByIdBranchData, ThrowOnError>,
): RequestResult<DeleteMembershipsByIdBranchResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteMembershipsByIdBranchResponses,
        unknown,
        ThrowOnError
    >({
        url: '/memberships/{id}/branch',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const postMembershipsByIdBranch = <ThrowOnError extends boolean = false>(
    options: Options<PostMembershipsByIdBranchData, ThrowOnError>,
): RequestResult<PostMembershipsByIdBranchResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostMembershipsByIdBranchResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postMembershipsByIdBranchResponseTransformer,
        url: '/memberships/{id}/branch',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getMembershipsBranchById = <ThrowOnError extends boolean = false>(
    options: Options<GetMembershipsBranchByIdData, ThrowOnError>,
): RequestResult<GetMembershipsBranchByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetMembershipsBranchByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getMembershipsBranchByIdResponseTransformer,
        url: '/memberships/branch/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getMembershipsMy = <ThrowOnError extends boolean = false>(
    options?: Options<GetMembershipsMyData, ThrowOnError>,
): RequestResult<GetMembershipsMyResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetMembershipsMyResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getMembershipsMyResponseTransformer,
        url: '/memberships/my',
        ...options,
    })

export const getMembershipsByIdPermissions = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetMembershipsByIdPermissionsData, ThrowOnError>,
): RequestResult<
    GetMembershipsByIdPermissionsResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetMembershipsByIdPermissionsResponses,
        unknown,
        ThrowOnError
    >({ url: '/memberships/{id}/permissions', ...options })

export const deleteMemberships = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteMembershipsData, ThrowOnError>,
): RequestResult<DeleteMembershipsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).delete<
        DeleteMembershipsResponses,
        unknown,
        ThrowOnError
    >({
        url: '/memberships',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const getMemberships = <ThrowOnError extends boolean = false>(
    options?: Options<GetMembershipsData, ThrowOnError>,
): RequestResult<GetMembershipsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetMembershipsResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getMembershipsResponseTransformer,
        url: '/memberships',
        ...options,
    })

export const postMemberships = <ThrowOnError extends boolean = false>(
    options?: Options<PostMembershipsData, ThrowOnError>,
): RequestResult<PostMembershipsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostMembershipsResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postMembershipsResponseTransformer,
        url: '/memberships',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const deleteMembershipsById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteMembershipsByIdData, ThrowOnError>,
): RequestResult<DeleteMembershipsByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteMembershipsByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: deleteMembershipsByIdResponseTransformer,
        url: '/memberships/{id}',
        ...options,
    })

export const getMembershipsById = <ThrowOnError extends boolean = false>(
    options: Options<GetMembershipsByIdData, ThrowOnError>,
): RequestResult<GetMembershipsByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetMembershipsByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getMembershipsByIdResponseTransformer,
        url: '/memberships/{id}',
        ...options,
    })

export const putMembershipsByIdChangeId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PutMembershipsByIdChangeIdData, ThrowOnError>,
): RequestResult<PutMembershipsByIdChangeIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutMembershipsByIdChangeIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/memberships/{id}/change-id',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getOrganizationsByUserByUserId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetOrganizationsByUserByUserIdData, ThrowOnError>,
): RequestResult<
    GetOrganizationsByUserByUserIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetOrganizationsByUserByUserIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getOrganizationsByUserByUserIdResponseTransformer,
        url: '/organizations/by-user/{userId}',
        ...options,
    })

export const getOrganizationsByOwnerByUserId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetOrganizationsByOwnerByUserIdData, ThrowOnError>,
): RequestResult<
    GetOrganizationsByOwnerByUserIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetOrganizationsByOwnerByUserIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getOrganizationsByOwnerByUserIdResponseTransformer,
        url: '/organizations/by-owner/{userId}',
        ...options,
    })

export const getOrganizationsByOrganizationIdMembers = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetOrganizationsByOrganizationIdMembersData, ThrowOnError>,
): RequestResult<
    GetOrganizationsByOrganizationIdMembersResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetOrganizationsByOrganizationIdMembersResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            getOrganizationsByOrganizationIdMembersResponseTransformer,
        url: '/organizations/{organizationId}/members',
        ...options,
    })

export const getOrganizationsByOrganizationIdCreator = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetOrganizationsByOrganizationIdCreatorData, ThrowOnError>,
): RequestResult<
    GetOrganizationsByOrganizationIdCreatorResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetOrganizationsByOrganizationIdCreatorResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            getOrganizationsByOrganizationIdCreatorResponseTransformer,
        url: '/organizations/{organizationId}/creator',
        ...options,
    })

export const getOrganizations = <ThrowOnError extends boolean = false>(
    options?: Options<GetOrganizationsData, ThrowOnError>,
): RequestResult<GetOrganizationsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetOrganizationsResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getOrganizationsResponseTransformer,
        url: '/organizations',
        ...options,
    })

export const postOrganizations = <ThrowOnError extends boolean = false>(
    options?: Options<PostOrganizationsData, ThrowOnError>,
): RequestResult<PostOrganizationsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostOrganizationsResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postOrganizationsResponseTransformer,
        url: '/organizations',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const deleteOrganizationsById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteOrganizationsByIdData, ThrowOnError>,
): RequestResult<DeleteOrganizationsByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteOrganizationsByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: deleteOrganizationsByIdResponseTransformer,
        url: '/organizations/{id}',
        ...options,
    })

export const getOrganizationsById = <ThrowOnError extends boolean = false>(
    options: Options<GetOrganizationsByIdData, ThrowOnError>,
): RequestResult<GetOrganizationsByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetOrganizationsByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getOrganizationsByIdResponseTransformer,
        url: '/organizations/{id}',
        ...options,
    })

export const putOrganizationsById = <ThrowOnError extends boolean = false>(
    options: Options<PutOrganizationsByIdData, ThrowOnError>,
): RequestResult<PutOrganizationsByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutOrganizationsByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: putOrganizationsByIdResponseTransformer,
        url: '/organizations/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const putOrganizationsByIdChangeId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PutOrganizationsByIdChangeIdData, ThrowOnError>,
): RequestResult<
    PutOrganizationsByIdChangeIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).put<
        PutOrganizationsByIdChangeIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/organizations/{id}/change-id',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getPermissions = <ThrowOnError extends boolean = false>(
    options?: Options<GetPermissionsData, ThrowOnError>,
): RequestResult<GetPermissionsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetPermissionsResponses,
        unknown,
        ThrowOnError
    >({ url: '/permissions', ...options })

export const postPermissions = <ThrowOnError extends boolean = false>(
    options?: Options<PostPermissionsData, ThrowOnError>,
): RequestResult<PostPermissionsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostPermissionsResponses,
        unknown,
        ThrowOnError
    >({
        url: '/permissions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const deletePermissionsById = <ThrowOnError extends boolean = false>(
    options: Options<DeletePermissionsByIdData, ThrowOnError>,
): RequestResult<DeletePermissionsByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeletePermissionsByIdResponses,
        unknown,
        ThrowOnError
    >({ url: '/permissions/{id}', ...options })

export const getPermissionsById = <ThrowOnError extends boolean = false>(
    options: Options<GetPermissionsByIdData, ThrowOnError>,
): RequestResult<GetPermissionsByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetPermissionsByIdResponses,
        unknown,
        ThrowOnError
    >({ url: '/permissions/{id}', ...options })

export const putPermissionsById = <ThrowOnError extends boolean = false>(
    options: Options<PutPermissionsByIdData, ThrowOnError>,
): RequestResult<PutPermissionsByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutPermissionsByIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/permissions/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getProjects = <ThrowOnError extends boolean = false>(
    options?: Options<GetProjectsData, ThrowOnError>,
): RequestResult<GetProjectsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetProjectsResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getProjectsResponseTransformer,
        url: '/projects',
        ...options,
    })

export const postProjects = <ThrowOnError extends boolean = false>(
    options?: Options<PostProjectsData, ThrowOnError>,
): RequestResult<PostProjectsResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostProjectsResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postProjectsResponseTransformer,
        url: '/projects',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const deleteProjectsByProjectId = <ThrowOnError extends boolean = false>(
    options: Options<DeleteProjectsByProjectIdData, ThrowOnError>,
): RequestResult<DeleteProjectsByProjectIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteProjectsByProjectIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: deleteProjectsByProjectIdResponseTransformer,
        url: '/projects/{projectId}',
        ...options,
    })

export const getProjectsByProjectId = <ThrowOnError extends boolean = false>(
    options: Options<GetProjectsByProjectIdData, ThrowOnError>,
): RequestResult<GetProjectsByProjectIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetProjectsByProjectIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getProjectsByProjectIdResponseTransformer,
        url: '/projects/{projectId}',
        ...options,
    })

export const putProjectsByProjectId = <ThrowOnError extends boolean = false>(
    options: Options<PutProjectsByProjectIdData, ThrowOnError>,
): RequestResult<PutProjectsByProjectIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutProjectsByProjectIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: putProjectsByProjectIdResponseTransformer,
        url: '/projects/{projectId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const putProjectsByProjectIdChangeId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PutProjectsByProjectIdChangeIdData, ThrowOnError>,
): RequestResult<
    PutProjectsByProjectIdChangeIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).put<
        PutProjectsByProjectIdChangeIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/projects/{projectId}/change-id',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const deleteRolesByIdPermissions = <
    ThrowOnError extends boolean = false,
>(
    options: Options<DeleteRolesByIdPermissionsData, ThrowOnError>,
): RequestResult<DeleteRolesByIdPermissionsResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteRolesByIdPermissionsResponses,
        unknown,
        ThrowOnError
    >({
        url: '/roles/{id}/permissions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getRolesByIdPermissions = <ThrowOnError extends boolean = false>(
    options: Options<GetRolesByIdPermissionsData, ThrowOnError>,
): RequestResult<GetRolesByIdPermissionsResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetRolesByIdPermissionsResponses,
        unknown,
        ThrowOnError
    >({ url: '/roles/{id}/permissions', ...options })

export const postRolesByIdPermissions = <ThrowOnError extends boolean = false>(
    options: Options<PostRolesByIdPermissionsData, ThrowOnError>,
): RequestResult<PostRolesByIdPermissionsResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostRolesByIdPermissionsResponses,
        unknown,
        ThrowOnError
    >({
        url: '/roles/{id}/permissions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getRolesByIdUsers = <ThrowOnError extends boolean = false>(
    options: Options<GetRolesByIdUsersData, ThrowOnError>,
): RequestResult<GetRolesByIdUsersResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetRolesByIdUsersResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getRolesByIdUsersResponseTransformer,
        url: '/roles/{id}/users',
        ...options,
    })

export const getRoles = <ThrowOnError extends boolean = false>(
    options?: Options<GetRolesData, ThrowOnError>,
): RequestResult<GetRolesResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<GetRolesResponses, unknown, ThrowOnError>({
        responseTransformer: getRolesResponseTransformer,
        url: '/roles',
        ...options,
    })

export const postRoles = <ThrowOnError extends boolean = false>(
    options?: Options<PostRolesData, ThrowOnError>,
): RequestResult<PostRolesResponses, PostRolesErrors, ThrowOnError> =>
    (options?.client ?? client).post<
        PostRolesResponses,
        PostRolesErrors,
        ThrowOnError
    >({
        responseTransformer: postRolesResponseTransformer,
        url: '/roles',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const deleteRolesById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteRolesByIdData, ThrowOnError>,
): RequestResult<DeleteRolesByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteRolesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: deleteRolesByIdResponseTransformer,
        url: '/roles/{id}',
        ...options,
    })

export const getRolesById = <ThrowOnError extends boolean = false>(
    options: Options<GetRolesByIdData, ThrowOnError>,
): RequestResult<GetRolesByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetRolesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getRolesByIdResponseTransformer,
        url: '/roles/{id}',
        ...options,
    })

export const putRolesById = <ThrowOnError extends boolean = false>(
    options: Options<PutRolesByIdData, ThrowOnError>,
): RequestResult<PutRolesByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutRolesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: putRolesByIdResponseTransformer,
        url: '/roles/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const putRolesByIdChangeId = <ThrowOnError extends boolean = false>(
    options: Options<PutRolesByIdChangeIdData, ThrowOnError>,
): RequestResult<PutRolesByIdChangeIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutRolesByIdChangeIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/roles/{id}/change-id',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getSecretKeys = <ThrowOnError extends boolean = false>(
    options?: Options<GetSecretKeysData, ThrowOnError>,
): RequestResult<GetSecretKeysResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetSecretKeysResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getSecretKeysResponseTransformer,
        url: '/secret-keys',
        ...options,
    })

export const postSecretKeys = <ThrowOnError extends boolean = false>(
    options?: Options<PostSecretKeysData, ThrowOnError>,
): RequestResult<PostSecretKeysResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostSecretKeysResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postSecretKeysResponseTransformer,
        url: '/secret-keys',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const deleteSecretKeysById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteSecretKeysByIdData, ThrowOnError>,
): RequestResult<DeleteSecretKeysByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteSecretKeysByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: deleteSecretKeysByIdResponseTransformer,
        url: '/secret-keys/{id}',
        ...options,
    })

export const getSecretKeysById = <ThrowOnError extends boolean = false>(
    options: Options<GetSecretKeysByIdData, ThrowOnError>,
): RequestResult<GetSecretKeysByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetSecretKeysByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getSecretKeysByIdResponseTransformer,
        url: '/secret-keys/{id}',
        ...options,
    })

export const postUsersByIdIdentifierAdd = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PostUsersByIdIdentifierAddData, ThrowOnError>,
): RequestResult<PostUsersByIdIdentifierAddResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostUsersByIdIdentifierAddResponses,
        unknown,
        ThrowOnError
    >({
        url: '/users/{id}/identifier/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const postUsersByIdIdentifierDelete = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PostUsersByIdIdentifierDeleteData, ThrowOnError>,
): RequestResult<
    PostUsersByIdIdentifierDeleteResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).post<
        PostUsersByIdIdentifierDeleteResponses,
        unknown,
        ThrowOnError
    >({
        url: '/users/{id}/identifier/delete',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getUsersByIdIdentifiers = <ThrowOnError extends boolean = false>(
    options: Options<GetUsersByIdIdentifiersData, ThrowOnError>,
): RequestResult<GetUsersByIdIdentifiersResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetUsersByIdIdentifiersResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getUsersByIdIdentifiersResponseTransformer,
        url: '/users/{id}/identifiers',
        ...options,
    })

export const postUserPasswordsUpsert = <ThrowOnError extends boolean = false>(
    options?: Options<PostUserPasswordsUpsertData, ThrowOnError>,
): RequestResult<PostUserPasswordsUpsertResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostUserPasswordsUpsertResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postUserPasswordsUpsertResponseTransformer,
        url: '/user-passwords/upsert',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const getUserPasswords = <ThrowOnError extends boolean = false>(
    options: Options<GetUserPasswordsData, ThrowOnError>,
): RequestResult<GetUserPasswordsResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetUserPasswordsResponses,
        unknown,
        ThrowOnError
    >({ url: '/user-passwords', ...options })

export const postUsersVerifyByToken = <ThrowOnError extends boolean = false>(
    options: Options<PostUsersVerifyByTokenData, ThrowOnError>,
): RequestResult<PostUsersVerifyByTokenResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostUsersVerifyByTokenResponses,
        unknown,
        ThrowOnError
    >({ url: '/users/verify/{token}', ...options })

export const postUsersByIdNewVerificationToken = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PostUsersByIdNewVerificationTokenData, ThrowOnError>,
): RequestResult<
    PostUsersByIdNewVerificationTokenResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).post<
        PostUsersByIdNewVerificationTokenResponses,
        unknown,
        ThrowOnError
    >({
        url: '/users/{id}/new-verification-token',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const deleteUsersByIdMembershipsByMembershipId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        DeleteUsersByIdMembershipsByMembershipIdData,
        ThrowOnError
    >,
): RequestResult<
    DeleteUsersByIdMembershipsByMembershipIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).delete<
        DeleteUsersByIdMembershipsByMembershipIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            deleteUsersByIdMembershipsByMembershipIdResponseTransformer,
        url: '/users/{id}/memberships/{membershipId}',
        ...options,
    })

export const postUsersPasswordForgot = <ThrowOnError extends boolean = false>(
    options: Options<PostUsersPasswordForgotData, ThrowOnError>,
): RequestResult<PostUsersPasswordForgotResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostUsersPasswordForgotResponses,
        unknown,
        ThrowOnError
    >({
        url: '/users/password/forgot',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const postUsersPasswordResetByToken = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PostUsersPasswordResetByTokenData, ThrowOnError>,
): RequestResult<
    PostUsersPasswordResetByTokenResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).post<
        PostUsersPasswordResetByTokenResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postUsersPasswordResetByTokenResponseTransformer,
        url: '/users/password/reset/{token}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const postUsersByIdPasswordChange = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PostUsersByIdPasswordChangeData, ThrowOnError>,
): RequestResult<PostUsersByIdPasswordChangeResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostUsersByIdPasswordChangeResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postUsersByIdPasswordChangeResponseTransformer,
        url: '/users/{id}/password/change',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const postUsersLogin = <ThrowOnError extends boolean = false>(
    options: Options<PostUsersLoginData, ThrowOnError>,
): RequestResult<PostUsersLoginResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostUsersLoginResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postUsersLoginResponseTransformer,
        url: '/users/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const postUsersLoginSwitch = <ThrowOnError extends boolean = false>(
    options?: Options<PostUsersLoginSwitchData, ThrowOnError>,
): RequestResult<PostUsersLoginSwitchResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostUsersLoginSwitchResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postUsersLoginSwitchResponseTransformer,
        url: '/users/login/switch',
        ...options,
    })

export const postUsersRegister = <ThrowOnError extends boolean = false>(
    options: Options<PostUsersRegisterData, ThrowOnError>,
): RequestResult<PostUsersRegisterResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostUsersRegisterResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: postUsersRegisterResponseTransformer,
        url: '/users/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const postUsersToken = <ThrowOnError extends boolean = false>(
    options: Options<PostUsersTokenData, ThrowOnError>,
): RequestResult<PostUsersTokenResponses, unknown, ThrowOnError> =>
    (options.client ?? client).post<
        PostUsersTokenResponses,
        unknown,
        ThrowOnError
    >({
        url: '/users/token',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const postUsersLogout = <ThrowOnError extends boolean = false>(
    options?: Options<PostUsersLogoutData, ThrowOnError>,
): RequestResult<PostUsersLogoutResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<
        PostUsersLogoutResponses,
        unknown,
        ThrowOnError
    >({ url: '/users/logout', ...options })

export const getUsersMe = <ThrowOnError extends boolean = false>(
    options?: Options<GetUsersMeData, ThrowOnError>,
): RequestResult<GetUsersMeResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<GetUsersMeResponses, unknown, ThrowOnError>(
        {
            responseTransformer: getUsersMeResponseTransformer,
            url: '/users/me',
            ...options,
        },
    )

export const getUsersCustomActive = <ThrowOnError extends boolean = false>(
    options?: Options<GetUsersCustomActiveData, ThrowOnError>,
): RequestResult<GetUsersCustomActiveResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetUsersCustomActiveResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getUsersCustomActiveResponseTransformer,
        url: '/users/custom/active',
        ...options,
    })

export const getUsersCustomBanned = <ThrowOnError extends boolean = false>(
    options?: Options<GetUsersCustomBannedData, ThrowOnError>,
): RequestResult<GetUsersCustomBannedResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetUsersCustomBannedResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getUsersCustomBannedResponseTransformer,
        url: '/users/custom/banned',
        ...options,
    })

export const getUsersCustomUnverified = <ThrowOnError extends boolean = false>(
    options?: Options<GetUsersCustomUnverifiedData, ThrowOnError>,
): RequestResult<GetUsersCustomUnverifiedResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<
        GetUsersCustomUnverifiedResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getUsersCustomUnverifiedResponseTransformer,
        url: '/users/custom/unverified',
        ...options,
    })

export const getUsersCustomInactive = <ThrowOnError extends boolean = false>(
    options: Options<GetUsersCustomInactiveData, ThrowOnError>,
): RequestResult<GetUsersCustomInactiveResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetUsersCustomInactiveResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getUsersCustomInactiveResponseTransformer,
        url: '/users/custom/inactive',
        ...options,
    })

export const deleteUsers = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteUsersData, ThrowOnError>,
): RequestResult<DeleteUsersResponses, DeleteUsersErrors, ThrowOnError> =>
    (options?.client ?? client).delete<
        DeleteUsersResponses,
        DeleteUsersErrors,
        ThrowOnError
    >({
        url: '/users',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers,
        },
    })

export const getUsers = <ThrowOnError extends boolean = false>(
    options?: Options<GetUsersData, ThrowOnError>,
): RequestResult<GetUsersResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({
        responseTransformer: getUsersResponseTransformer,
        url: '/users',
        ...options,
    })

export const postUsers = <ThrowOnError extends boolean = false>(
    options?: Options<PostUsersData, ThrowOnError>,
): RequestResult<PostUsersResponses, unknown, ThrowOnError> =>
    (options?.client ?? client).post<PostUsersResponses, unknown, ThrowOnError>(
        {
            responseTransformer: postUsersResponseTransformer,
            url: '/users',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
            },
        },
    )

export const deleteUsersById = <ThrowOnError extends boolean = false>(
    options: Options<DeleteUsersByIdData, ThrowOnError>,
): RequestResult<DeleteUsersByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).delete<
        DeleteUsersByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: deleteUsersByIdResponseTransformer,
        url: '/users/{id}',
        ...options,
    })

export const getUsersById = <ThrowOnError extends boolean = false>(
    options: Options<GetUsersByIdData, ThrowOnError>,
): RequestResult<GetUsersByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).get<
        GetUsersByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: getUsersByIdResponseTransformer,
        url: '/users/{id}',
        ...options,
    })

export const putUsersById = <ThrowOnError extends boolean = false>(
    options: Options<PutUsersByIdData, ThrowOnError>,
): RequestResult<PutUsersByIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutUsersByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer: putUsersByIdResponseTransformer,
        url: '/users/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const putUsersByIdChangeId = <ThrowOnError extends boolean = false>(
    options: Options<PutUsersByIdChangeIdData, ThrowOnError>,
): RequestResult<PutUsersByIdChangeIdResponses, unknown, ThrowOnError> =>
    (options.client ?? client).put<
        PutUsersByIdChangeIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/users/{id}/change-id',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const getOrganizationsByOrganizationIdZonesMy = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetOrganizationsByOrganizationIdZonesMyData, ThrowOnError>,
): RequestResult<
    GetOrganizationsByOrganizationIdZonesMyResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetOrganizationsByOrganizationIdZonesMyResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            getOrganizationsByOrganizationIdZonesMyResponseTransformer,
        url: '/organizations/{organizationId}/zones/my',
        ...options,
    })

export const getOrganizationsByOrganizationIdZones = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetOrganizationsByOrganizationIdZonesData, ThrowOnError>,
): RequestResult<
    GetOrganizationsByOrganizationIdZonesResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetOrganizationsByOrganizationIdZonesResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            getOrganizationsByOrganizationIdZonesResponseTransformer,
        url: '/organizations/{organizationId}/zones',
        ...options,
    })

export const postOrganizationsByOrganizationIdZones = <
    ThrowOnError extends boolean = false,
>(
    options: Options<PostOrganizationsByOrganizationIdZonesData, ThrowOnError>,
): RequestResult<
    PostOrganizationsByOrganizationIdZonesResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).post<
        PostOrganizationsByOrganizationIdZonesResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            postOrganizationsByOrganizationIdZonesResponseTransformer,
        url: '/organizations/{organizationId}/zones',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const deleteOrganizationsByOrganizationIdZonesById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        DeleteOrganizationsByOrganizationIdZonesByIdData,
        ThrowOnError
    >,
): RequestResult<
    DeleteOrganizationsByOrganizationIdZonesByIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).delete<
        DeleteOrganizationsByOrganizationIdZonesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            deleteOrganizationsByOrganizationIdZonesByIdResponseTransformer,
        url: '/organizations/{organizationId}/zones/{id}',
        ...options,
    })

export const getOrganizationsByOrganizationIdZonesById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetOrganizationsByOrganizationIdZonesByIdData,
        ThrowOnError
    >,
): RequestResult<
    GetOrganizationsByOrganizationIdZonesByIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).get<
        GetOrganizationsByOrganizationIdZonesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            getOrganizationsByOrganizationIdZonesByIdResponseTransformer,
        url: '/organizations/{organizationId}/zones/{id}',
        ...options,
    })

export const putOrganizationsByOrganizationIdZonesById = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        PutOrganizationsByOrganizationIdZonesByIdData,
        ThrowOnError
    >,
): RequestResult<
    PutOrganizationsByOrganizationIdZonesByIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).put<
        PutOrganizationsByOrganizationIdZonesByIdResponses,
        unknown,
        ThrowOnError
    >({
        responseTransformer:
            putOrganizationsByOrganizationIdZonesByIdResponseTransformer,
        url: '/organizations/{organizationId}/zones/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

export const putOrganizationsByOrganizationIdZonesByIdChangeId = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        PutOrganizationsByOrganizationIdZonesByIdChangeIdData,
        ThrowOnError
    >,
): RequestResult<
    PutOrganizationsByOrganizationIdZonesByIdChangeIdResponses,
    unknown,
    ThrowOnError
> =>
    (options.client ?? client).put<
        PutOrganizationsByOrganizationIdZonesByIdChangeIdResponses,
        unknown,
        ThrowOnError
    >({
        url: '/organizations/{organizationId}/zones/{id}/change-id',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })
